### PR TITLE
[TASK] Use yaml_parse instead of yaml_parse_file

### PR DESCRIPTION
**Pull request by kdambekalns**
If the PECL yaml extension is used, it was not possible to load YAML
configuration files from 'resource://some/path' while this worked for
the Symfony YAML parser.

To align the functionality, the file content is now fetched using
file_get_contents() (which uses stream wrappers) and then passed to
yaml_parse().

### CODE REVIEW

**Comment by dfeyer** [comment]
:+1:

**Comment by aertmann** [comment]
Is this as performant as the direct call? Could imagine this uses more memory. An alternative is to check for "resource://" before doing the workaround.

**Comment by kdambekalns** [comment]
TBH I didn't check performance, and I guess it's about the same, since it needs to be loaded anyway.

So the question is, do we measure this now, or do we assume the gain (of making `resource://` work) is wirth it? The check you mention would be doable, but then again: is the check worth it, it might slow down the thing even more…

**Comment by kdambekalns** [comment]
@aertmann added a check for `resource://` as suggested

**Comment by aertmann** [comment]
:+1:  thanks

**Comment by kdambekalns** [comment]
@dfeyer fine with you this way?

**Comment by skurfuerst** [comment]
:+1: by reading. makes sense! Merging with previous votes, assuming @dfeyer has nothing against it ;)

**Pull request merged**
