### PR TITLE
BUGFIX: Query count with groupBy and join is off

### PR DESCRIPTION
**Pull request by albe**
FLOW-104 #close

### CODE REVIEW

**Comment by kdambekalns** [comment]
Now the failing Travis test actually shows a small, albeit real issue with this change… ;)

**Comment by albe** [comment]
This could actually be related to #416

**Comment by albe** [comment]
Ah, no that's nonsense. #416 only relevant for Query model

**Comment by kitsunet** [comment]
Is this still relevant?

**Comment by albe** [comment]
If the test still fails, yes. Guess a rebase would be good, but I doubt the behaviour changed.

**Pull request closed without merging**
