### PR TITLE
TASK: correct naming for setting

### PR DESCRIPTION
**Pull request by beardcoder**
Resolves #1410

**Checklist**

- [x] Code follows the PSR-2 coding style
- [x] Tests have been created, run and adjusted as needed
- [x] The PR is created against the [lowest maintained branch](https://www.neos.io/features/release-roadmap.html)

### CODE REVIEW

**Comment by albe** [comment]
Hey, thanks for this! I think this should be targeting 4.3 instead of master.

**Comment by beardcoder** [comment]
I liked to do that but i think this is a request for all releases.
At the moment you get an error in PHPStorm and other IDEs with validation support for the editorconfig.

**Comment by kitsunet** [comment]
> request for all releases

We follow an upmerge policy. So it must be merged to the lowest (version) branch this problem applies to and will then be upmerged from there.

**Comment by beardcoder** [comment]
Closed because of 

> We follow an upmerge policy. So it must be merged to the lowest (version) branch this problem applies to and will then be upmerged from there.

Correct PR is now https://github.com/neos/flow-development-collection/pull/1413

**Pull request closed without merging**
