### PR TITLE
TASK: RsaWalletService tweaks

### PR DESCRIPTION
**Pull request by kdambekalns**
Improves naming and documentation in RsaWalletService and the related command controller.

### CODE REVIEW

**Comment by kdambekalns** [comment]
@foerthner @hlubek

**Comment by foerthner** [comment]
Thanks for fixing the namings here. Totally makes sense by reading!

**Comment by hlubek** [comment]
:+1: by reading, maybe add a note into the docs on how to generate that fingerprint from a PEM-encoded (private) key?

**Comment by RafaelKa** [comment]
:+1:, but what about doc. comments and parameters in RsaWalletServiceInterface?

**Comment by kdambekalns** [comment]
@RafaelKa Yes, what about them?  Can you elaborate?

@hlubek With docs you mean CLI docs (docblock) or manual?

**Comment by kitsunet** [comment]
:+1: definitely an improvement. Will merge in 24h if no changes or objections.

**Comment by RafaelKa** [comment]
@kitsunet then #230 to at the same time ;)

**Pull request merged**
