### PR TITLE
TASK: Memcached cache backend compatibility with memcached

### PR DESCRIPTION
**Pull request by aertmann**
Adds support for the "memcached" extension in addition to the existing
support for the "memcache" extension.

"memcached" is a newer version with several improvements and often both
extensions aren't available simultaneously.

FLOW-440 #close

### CODE REVIEW

**Comment by aertmann** [comment]
not sure if this should be backported to stable versions, it's very low risk and a useful improvement

:+1: verified using the "memcached" extension

should be very safe to merge, since nothing should have changed for the "memcache" extension except if both are installed "memcached" is used since it's better

@kdambekalns @dfeyer maybe you have some interest in this area? thanks

**Comment by kdambekalns** [comment]
Very nice. Read through it and it seems indeed fit for inclusion in 2.3 and up IMHO.

**Comment by aertmann** [comment]
Pushed against 2.3 #296

**Comment by kitsunet** [comment]
Looks good and agree, could be backported.

**Pull request closed without merging**
