### PR TITLE
FEATURE: Extend DenormalizingObjectConverter to support fromBoolean and fromInteger

### PR DESCRIPTION
**Pull request by bwaidelich**
...in addition to their short version (`fromBool()` and `fromInt()`).
This also adds a short documentation about Value Object property mapping.

Related: #2763

### CODE REVIEW

**Review by mficzel — APPROVED** [review]
Fine by reading, huge thanks for the documentation fragment

**Comment by mficzel** [comment]
@bwaidelich the psalm issues should be addressed still

**Comment by bwaidelich** [comment]
>  the psalm issues should be addressed still

Doh, I never really know what to do with those.. can anyone help here?

**Comment by bwaidelich** [comment]
> Those messages always make sense in hindsight.

Well, it makes sense, because
```php
method_exists($targetType, 'someString');
```
can only work if `$targetType` is a `class-string` or an `object`..
But I'm surprised that it didn't trap over
```php
$targetType::fromBool($source);
```
before (since even PhpStorm complains about that part).

But, more importantly.. I don't know how to get rid of the message :)
I tried replacing `string` by `string-class` in the param annotation, but that bubbles up..

**Comment by mficzel** [comment]
Checking for class_exists convinced psalm. It is a bit redundant but i also agree that relying on the order methods are called ist also not great.

**Review by albe — APPROVED** [review]

**Comment by albe** [comment]
Thanks a lot!

**Comment by kdambekalns** [comment]
❤️

**Pull request merged**
