### PR TITLE
TASK: Add support for DateTimeImmutable classes mapping with doctrine

### PR DESCRIPTION
**Pull request by albe**
This change correctly maps `DateTimeImmutable` property types with doctrine.

Depends on #1442

### CODE REVIEW

**Comment by albe** [comment]
Damn :|

**Comment by albe** [comment]
Apparently, `datetime_immutable` is only available as of Doctrine DBAL 2.6, which we only added in Flow 5.0, since the former requires PHP 7.1

https://github.com/doctrine/dbal/releases/tag/v2.6.0

So I'm going to retarget this and then hopefully the tests pass.

**Comment by albe** [comment]
Argh, I discovered a bug in the TypeHandling. We currently try to parse types with a rather cumbersome regex, that eagerly matches `DateTime` and hence will parse a `DateTimeImmutable` var annotation as `DateTime` :(

**Comment by albe** [comment]
Generally yes, but in this case I'm considering it something between BUGFIX and FEATURE - hence the label "TASK". It should have been there all along since we upgraded to DBAL 2.7 in the 5.0 release IMO.

If the others also regard this as FEATURE, we can of course only merge this into master.

**Comment by bwaidelich** [comment]
> but in this case I'm considering it something between BUGFIX and FEATURE
I know, it's on the edge. But IMO there should be almost no tasks at all. It's almost always a (missing) feature or a bugfix. In this case I'd say it's the former.

Anyways, not to split hairs, and I'm fine with having that added in a patch level release (I thought it was a problem to backport it, but I misread your comment above)

**Comment by albe** [comment]
> I thought it was a problem to backport it

Nope, this change is really easy still, but it can only go into 5.0 minimum. But it depends on #1442 anyway, so we need to resolve that first.

**Comment by jonnitto** [comment]
@albe Can you fix the tests, so we can merge it?

**Comment by albe** [comment]
Dang, tests failed because the tests were run based on 4.3 branch still. Rebased and force pushed.

**Comment by albe** [comment]
Did upmerges to get #1442 into 5.0 and merged the change into this. Tests should now pass :crossed_fingers:

**Comment by albe** [comment]
Merging with previous votes

**Pull request merged**
