### PR TITLE
[TASK] Use DateTimeInterface in Flow

### PR DESCRIPTION
**Pull request by kitsunet**
Since Flow requires PHP 5.5 it should use and support the ``\DateTimeInterface``.
With support for it the ``Now`` class can extend from ``DateTimeImmutable`` to
prevent changes to the singleton throughout a request.

### CODE REVIEW

**Comment by kitsunet** [comment]
Note that this would break Neos if support for DateTimeInterface is not implemented there first, so do not merge yet.

**Comment by kdambekalns** [comment]
From the top of my head: 

* why not for 3.0, it should be BC
* wasn't there something about DateTimeInterface and HHVM (and/or PHP7)?

**Comment by kitsunet** [comment]
That's the matching Neos change: https://github.com/neos/neos-development-collection/pull/142
We could put it in 3.0 but I don't see a strong reason for it. Currently there is no bug that this would solve.
So just tell me if I should rebase to 3.0.

**Comment by albe** [comment]
:+1: from reading, couldn't find anything problematic about DateTimeInterface, but I'll be sure to check it out on our HHVM machine

**Comment by skurfuerst** [comment]
:+1: by reading; I merged Neos change beforehand so I am also merging this one. good work!

**Comment by bwaidelich** [comment]
I'm late to the party (again), but the `DateTimeConverter` should probably be adjusted, too.
Also `\TYPO3\Flow\Utility\Now` does not seem to play nice with PHP7 because it is not compatible with `\DateTime` any longer

**Comment by bwaidelich** [comment]
Ah, that hasn't got anything to to do with PHP7 I suppose but with this very change:
Code like
```
public function setDate(\DateTime $date) {
// ...
}
```
now needs to be adjusted to `\DateTimeInterface` but that breaks support for the `PropertyMapper`

**Comment by kitsunet** [comment]
Mmm, yes that is true, but then we need to fix that I suppose. A workaorund for now is to cast now to a DateTime

**Comment by kitsunet** [comment]
But that just shows we need more tests.

**Comment by albe** [comment]
Wait, what? DateTimeImmutable is not an instanceof DateTime? oh... PHP.... doing it wrong again :(

**Comment by kitsunet** [comment]
Nope and that is a good thing. You would expect something mutable if you expect DateTime. In that regard DateTimeImmutable IS different, so it would be possibly dangerous to make it an instance of DateTime.

**Comment by kitsunet** [comment]
https://github.com/neos/flow-development-collection/pull/167 for the partial revert.

**Pull request merged**
