### PR TITLE
!!! FEATURE: Update CLDR/main from 1.8 to version 38

### PR DESCRIPTION
**Pull request by daniellienert**
This updates the main locale-dependent LDML files to version 38
The format seems compatible. But content-wise a lot has changed.

New territories / countries / languages have been added and others, like
East-Germany have been removed.

‼ If you like to test it / run tests, you have to remove the CLDR caches manually. Otherwise you will test cached data:

eg: `rm -rf Data/Temporary/Testing/Cache/Data/Flow_I18n_*` 

see: #2116

### CODE REVIEW

**Comment by kdambekalns** [comment]
@daniellienert If you had given contributors access to this PR, I'd have pushed a follow-up, but… 🤷‍♂️

- merge in master (having #2117 now)
- the `PluralsReaderTest` needs to be fixed (see #2117 for details)
- `FormatResolverTest` fails, but that seems like an easy fix

**Comment by daniellienert** [comment]
@kdambekalns: Plurals reader test is fixed

**Comment by daniellienert** [comment]
@kdambekalns please have a look at https://github.com/neos/flow-development-collection/pull/2118/commits/4daaf25eced67545e30c64c440772049de94dba6. I only found the default set to `<default choice="long" draft="unconfirmed"/>` for Farsi.
What do you think?

**Comment by albe** [comment]
> @kdambekalns please have a look at [4daaf25](https://github.com/neos/flow-development-collection/commit/4daaf25eced67545e30c64c440772049de94dba6). I only found the default set to `<default choice="long" draft="unconfirmed"/>` for Farsi.
> What do you think?

Sounds reasonable to me.

**Comment by kdambekalns** [comment]
I agree to https://github.com/neos/flow-development-collection/commit/4daaf25eced67545e30c64c440772049de94dba6

**Comment by daniellienert** [comment]
I'll take care of the decimals reader currently which needs to determine the default numbering system.

**Comment by kdambekalns** [comment]
Ok, got fooled by the caching (despite the warning… _sigh_) But not tests pass for me.

@daniellienert what do you mean with this?

> I'll take care of the decimals reader currently which needs to determine the default numbering system.

**Comment by kdambekalns** [comment]
By now I am fully confused - Travis fails? And re-running all tests again locally fails, too, but with very different failures.

🤯

Cleared the cache on Travis, re-running a job to check…

**Comment by kdambekalns** [comment]
I'm out, I give up. At least for today…

**Comment by daniellienert** [comment]
> @daniellienert what do you mean with this?

Damn, now the CLDR cache tricked me! But I still see locally failing test.

**Comment by daniellienert** [comment]
Green! Really great to have all the tests!

Changes needed were pretty smooth after all. This one https://github.com/neos/flow-development-collection/pull/2118/commits/8bfd3cf1102d22c7cf2edd7e74c3365a6d5a3e3c is a bit dirty, but the case didn't fit to any rule.

**Review by kdambekalns — APPROVED** [review]
🎉

**Pull request merged**
