### PR TITLE
TASK: Use PhpUnit 6

### PR DESCRIPTION
**Pull request by kdambekalns**

### CODE REVIEW

**Comment by kdambekalns** [comment]
Most probably TravisCI will fail, since the dev dist requires PhpUnit 5.4 (see https://github.com/neos/flow-development-distribution/pull/20). I'll know after lunch…

**Comment by kdambekalns** [comment]
So @kitsunet merged the dist change and restarted the TravisCI build for this one (I think). All green!

**Comment by kdambekalns** [comment]
Now on to Neos… :)

**Comment by kitsunet** [comment]
Yes, Yes, that's what I did 👍 Thanks for emrging

**Pull request merged**
