### PR TITLE
BUGFIX: Check for link in unpublishFile()

### LINKED ISSUE #972: FileSystemSymlinkTarget fails to unpublish correctly
### Description

When unpublishing a resource, the file in `Data/Persistent/Resources/…` is removed correctly, but the symlink pointing to it below `Web/_Resources/Persistent/…` is left in place.

### Steps to Reproduce

1. Publish a file
2. Unpublish file

Note: this can easily be done by using the replace function on an asset in the Neos media management.

#### Expected behavior

The symlink is removed together with the "real" resource file.

#### Actual behavior

The symlink stays in place.

This leads to the rewrite rules "seeing" the requested file, even though it can non longer be served. One effect of this is redirects from the redirect handler are never even looked for.

### Affected Versions

Flow: 3.3.x and later

### PR DESCRIPTION
**Pull request by kdambekalns**
`unpublishFile()` in the `FileSystemTarget` does not remove symlinks
correctly, thus the method is adjusted in the `FileSystemSymlinkTarget`
to check using `is_link()` instead of `file_exists()`.

Fixes #972

### CODE REVIEW

**Comment by kdambekalns** [comment]
I did not add a test here, since vfsStream has no support for symlinks (last time I checked, at least).

**Comment by kdambekalns** [comment]
@kitsunet Which messages do you mean?

**Comment by kdambekalns** [comment]
Well, I cannot think of a way that involves less code, TBH. Except handling both cases in the parent, but that feels dirty.

**Comment by aertmann** [comment]
yeah it's a tough one, you could call the parent after first method, but that would mean it would do the first check twice of course

**Comment by aertmann** [comment]
not blocking it btw.

**Pull request merged**
