### PR TITLE
TASK: Update psalm-baseline.xml

### PR DESCRIPTION
**Pull request by kdambekalns**
The new errors look like false positives, at least so much I wouldn't
risk a change for them…

### CODE REVIEW

**Comment by kdambekalns** [comment]
How can psalm fail with the very errors this should fix? 🤔

**Comment by daniellienert** [comment]
@kdambekalns, looks like if you updated the baseline with the Neos Dev-Distribution installed.

**Comment by kdambekalns** [comment]
> looks like if you updated the baseline with the Neos Dev-Distribution installed.

Yes, but that's what I always did so far. 🤔

**Comment by kdambekalns** [comment]
So, the trick is… to use PHP 7.2 as the test does on Travis. When updating the baseline with PHP 7.4, the build fails like this.

**Comment by albe** [comment]
> So, the trick is… to use PHP 7.2 as the test does on Travis. When updating the baseline with PHP 7.4, the build fails like this.

D'oh :| Another good reason that we somehow find a solution to "fix" psalm through the pipeline. Maybe another look at GitHub actions could work. Or a job on the jenkins that can be manually triggered?

**Pull request merged**
