### PR TITLE
BUGFIX: Logger::logThrowable will return a message

### PR DESCRIPTION
**Pull request by dfeyer**

### CODE REVIEW

**Comment by kitsunet** [comment]
You could probably also just really return the message from the storage.

**Comment by kitsunet** [comment]
Problem is that only the storage knows how to find the stored item. So it must give some info back for the logger.

**Comment by dfeyer** [comment]
@kitsunet Ok, Interface updated the Storage now return the message, make sense

**Comment by dfeyer** [comment]
@kdambekalns Done

**Comment by kdambekalns** [comment]
BTW… why is this in Flow, not in Flow.Log?

**Comment by kitsunet** [comment]
Because for now I wanted to have storing of throwables separated from logging. It's a different concern (and my evil secret plan to replace logging with monolog at some point would be much harder that way, because we want to keep storing exception details I guess :D)

**Pull request merged**
