### PR TITLE
BUGFIX: Wrong time format in log FileBackend - #3121

### LINKED ISSUE #3121: BUG: Since a recent commit, the date and time logged into the System.log is wrong
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

After a recent commit, the date and time logged into the `System.log` is wrong. Instead of logging the following correct date and time:

`Year-Month-Day Hour-Minute-Second`

the following is logged:

`Year-Month-Day Hour-Month-Minute`

### Expected Behavior

Logging of the following format  (_as before the commit_):

`Year-Month-Day Hour-Minute-Second`

### Steps To Reproduce

Logging something into the `System.log`.

### Environment

```markdown
- Flow: 8.3.3
- PHP: 8.2.8
```

### Anything else?

In a recent commit the creation of the current date and time changed from the `date()` function to `DateTime()->format()` function. The formatter passed to the `DateTime()->format()` function is wrong:

Problematic file:
`Packages/Libraries/neos/flow-log/Classes/Backend/FileBackend.php:244`

Before fix:
```php
$output = (new \DateTime())->format('y-m-d H:m:i') . $processId . ' ' . $ipAddress . $severityLabel . ' ' . str_pad((string)$packageKey, 20) . ' ' . $message;
```

After fix:
```php
$output = (new \DateTime())->format('y-m-d H:i:s') . $processId . ' ' . $ipAddress . $severityLabel . ' ' . str_pad((string)$packageKey, 20) . ' ' . $message;
```

### PR DESCRIPTION
**Pull request by mhsdesign**
Fixes a regression from https://github.com/neos/flow-development-collection/pull/3094

Fixes: #3121

**Checklist**

- [x] Code follows the PSR-2 coding style
- [x] Tests have been created, run and adjusted as needed
- [x] The PR is created against the [lowest maintained branch](https://www.neos.io/features/release-roadmap.html)

### CODE REVIEW

**Review by kdambekalns — APPROVED** [review]
🙈

**Review by ahaeslich — APPROVED** [review]

**Comment by mhsdesign** [comment]
Ah we still need a test. And confirmation that this fix actually works - i didnt test it locally ;) (yet)

**Comment by ahaeslich** [comment]
> And confirmation that this fix actually works - i didnt test it locally 

Well as I stumbled upon this again: checked locally. Works as expected 😉 ❤️

**Comment by mhsdesign** [comment]
thx @ahaeslich ^^

**Pull request merged**
