### PR TITLE
TASK: Include the application context in cache keys

### PR DESCRIPTION
**Pull request by daniellienert**
resolves: #2618

- Refactors the applicationContextHash to be available for all backends
- Use the application context in pdo and redis backend

### CODE REVIEW

**Comment by daniellienert** [comment]
Happy to discuss, if this is considered a bugfix or a breaking change :)

**Comment by kitsunet** [comment]
Sounds like a bugfix to me. we might consider thinking about this in a larger context, I think atm each backend decides for itself if and how to apply this information.

**Review by kdambekalns — APPROVED** [review]
Looks good and like a bugfix. Are there more backends to fix, potentially?

**Comment by daniellienert** [comment]
@kdambekalns all other backends are fine
@kitsunet I am open for suggestions. Seemed to me, that other backends vary the cache key generation depending on their backend technology

**Comment by gerhard-boden** [comment]
Thanks for the fix!
Since 90% of our projects run on the PdoBackend (SQLite) I'm very happy to untertake some real world testing
If I understand the problem correctly the backend would not differentiate between production and dev context for example?

**Comment by daniellienert** [comment]
> Thanks for the fix! Since 90% of our projects run on the PdoBackend (SQLite)
@gerhard-boden The PDO backend already respected the context - you are safe :)

**Comment by daniellienert** [comment]
Closed in favor of #2622

**Comment by gerhard-boden** [comment]
> > Thanks for the fix! Since 90% of our projects run on the PdoBackend (SQLite)
> > @gerhard-boden The PDO backend already respected the context - you are safe :)

ah thanks for the info 😄 , thought this had something to do with it https://github.com/neos/flow-development-collection/pull/2619/files#diff-43cc6c26a0807aa1ab29bebc0bfcfcb50fafba53bcb2443830a160b6185162a5

**Pull request closed without merging**
