### PR TITLE
TASK: Add translation for error message (string length)

### PR DESCRIPTION
**Pull request by responsemlanger**
[Task] Add translation for exceeding maximum string length

### CODE REVIEW

**Comment by albe** [comment]
:+1:

**Comment by kitsunet** [comment]
:-1: Our translations are handled by https://crowdin.com/project/neos
You would need to add the translation there please.

**Comment by responsemlanger** [comment]
Thanks a lot for the information. The translation is already available since 5 months ("This text may not exceed {0,number} character"), but the translation of 1238108068 and 1238108069 is empty in the german xliff file. Is this a bug?

**Comment by kitsunet** [comment]
@kdambekalns maybe you can have a look? Probably something wrong with the synchronization of translations from crowdin.

**Comment by kitsunet** [comment]
@kdambekalns Any news on this?

**Comment by kdambekalns** [comment]
I have no idea why this is empty. The string is correctly translated according to Crowdin…

I created https://github.com/neos/flow-development-collection/pull/340, since this is broken in 3.0 and up.

**Pull request closed without merging**
