### PR TITLE
BUGFIX `var_dump` skip static properties

### LINKED ISSUE #4321: 9.0 Var dumping `NodeTypeName` f.x. will also show all instances
due to the static $instances we will totally spam the whole output:

image

this is just an example, it gets worse if you try to dump a nodeType or a node ;)

… it’s not a good developer experience and I’m wondering what we could do about it 

maybe:
- store the instances some place else
- Or don’t include them in flows var_dump (or cut off the output like that instances contains an array of NodeTypes)

reproduction:

```php
\Neos\ContentRepository\Core\NodeType\NodeTypeName::fromString("Vendor.Site:BliBlub");
$a = \Neos\ContentRepository\Core\NodeType\NodeTypeName::fromString("Vendor.Site:Bar");

var_dump($a);

print_r($a);

\Neos\Flow\var_dump($a);
```

image

you can see that `var_dump` will ignore instance properties as well - maybe we should also simply do this.

### PR DESCRIPTION
**Pull request by mhsdesign**
Solves https://github.com/neos/neos-development-collection/issues/4321

**Upgrade instructions**

**Review instructions**

**Checklist**

- [ ] Code follows the PSR-2 coding style
- [ ] Tests have been created, run and adjusted as needed
- [ ] The PR is created against the [lowest maintained branch](https://www.neos.io/features/release-roadmap.html)
- [ ] Reviewer - PR Title is brief but complete and starts with `FEATURE|TASK|BUGFIX`
- [ ] Reviewer - The first section explains the change briefly for change-logs
- [ ] Reviewer - Breaking Changes are marked wit `!!!` and have upgrade-instructions

### CODE REVIEW

**Review by kdambekalns — DISMISSED** [review]
Not sure. What if I want to know what a static property contains? Assuming it's not important seems too simple. No?

**Comment by mhsdesign** [comment]
This is the same behavior as in php's `var_dump` and i assume its fine?

**Comment by kdambekalns** [comment]
> This is the same behavior as in php's `var_dump` and i assume its fine?

Is it? 😑 I'll try that. But it's not always the case that PHP chose the best way to solve a problem. 😇

**Review by bwaidelich — APPROVED** [review]
Makes sense to me (see https://github.com/neos/neos-development-collection/issues/4321)

**Review by kitsunet — APPROVED** [review]
I am fine with this too I think :)

**Comment by mhsdesign** [comment]
Thänks ❤️

**Pull request merged**
