### PR TITLE
BUGFIX: Fix truncation of cache file when lock not acquired

### PR DESCRIPTION
**Pull request by christianharrington**
Previously, SimpleFileBackend would truncate the contents of the cache file if it couldn't acquire the lock.

To fix this, the `c` flag is used for `fopen`, so the file is not truncated if it already exists. This necessitates that we manually truncate the file if the lock is acquired.

I've added a test that fails without these changes, and passes with them.

**Checklist**

- [x] Code follows the PSR-2 coding style
- [x] Tests have been created, run and adjusted as needed
- [x] The PR is created against the [lowest maintained branch](https://www.neos.io/features/release-roadmap.html)
- [ ] Reviewer - PR Title is brief but complete and starts with `FEATURE|TASK|BUGFIX`
- [ ] Reviewer - The first section explains the change briefly for change-logs
- [ ] Reviewer - Breaking Changes are marked wit `!!!` and have upgrade-instructions

### CODE REVIEW

**Review by kdambekalns — COMMENTED** [review]
Looks good by reading. Good catch!

**Review by kitsunet — APPROVED** [review]

**Comment by kitsunet** [comment]
Indeed great catch.

**Comment by kitsunet** [comment]
waiting for ci would merge then.

**Comment by christianharrington** [comment]
I think the failing CI check is unrelated. Let me know if I need to do anything.

**Comment by christianharrington** [comment]
@kdambekalns @kitsunet I would love to get this merged in. Is there anything I can do to help?

**Comment by christianharrington** [comment]
@kdambekalns 
With #2934 merged, this bug should no longer cause an exception directly (since `fread` will not be called with length 0), but will instead cause `get` to return an unexpected value (`false`, I believe, since `unserialize('') === false`).

This could introduce subtle bugs in code calling `get` but not checking the returned value, such as in [CldrModel](https://github.com/neos/flow-development-collection/blob/aeff374ffb973f7f597da3f106be3d252f9a2639/Neos.Flow/Classes/I18n/Cldr/CldrModel.php#L109-L110).

In our production application, this race-condition is triggered many times each day, so I would love to see this fix get merged.

**Comment by kdambekalns** [comment]
@christianharrington Thanks for the reminder, I had completely forgotten about this one! Sorry!

**Pull request merged**
