### PR TITLE
FEATURE: Add Tideways instrumentation for bootstrap process

### PR DESCRIPTION
**Pull request by kdambekalns**
This adds Tideways instrumentation to the Flow bootstrapping.

### CODE REVIEW

**Comment by kdambekalns** [comment]
My major concern: can we somehow move this to an external package? The parts of the code that are adjusted are not really reachable via `Package::boot()` or AOP, so… any other ideas?

**Comment by kdambekalns** [comment]
Ah, see also https://github.com/tideways/profiler/pull/6 and https://github.com/tideways/php-profiler-extension/pull/32

**Comment by kitsunet** [comment]
Oh and IF everyone else should decide that we could merge this, then clearly not in 3.3 but in master.

**Comment by kdambekalns** [comment]
As I wrote:

> My major concern: can we somehow move this to an external package?

Also, _WIP_ and _Help needed_ for the very same reason. So…

And no, external `Package` class is too late, at least if using the `boot` method. I could just put watch calls into the global scope inside such a `Package.php`… Might be worth a try, **but** violates autoloading rules and CGL (side-effect free class files.)

**Comment by bwaidelich** [comment]
I'd also prefer a more general way to hook into bootstrapping for these kind of things
Couldn't we introduce some signals for that or is that too late as well`

**Comment by jonnitto** [comment]
Any progress on this or should we close this one?

**Pull request closed without merging**
