### PR TITLE
TASK: Make XliffTranslationProvider use locale chain

### PR DESCRIPTION
**Pull request by ComiR**
This change makes `getTranslationById` and `getTranslationByOriginalLabel` use the configured
locale chain.

Replaces #324, succession by #327 needs to be discussed.

FLOW-356 #close

### CODE REVIEW

**Comment by albe** [comment]
Tests need a proper LocaleChain mock it seems, other than that looks good. I can take care of the tests if no one else does beforehand.

**Comment by albe** [comment]
Created a PR on your fork for the tests. Would be cool if you could allow all Neos team members push access to your fork to improve working together.

**Comment by albe** [comment]
So, looks good for me :+1:

**Comment by kdambekalns** [comment]
One thing that bothers me out of the box: now `getTranslationBy…` loops over the locale chain and in turn calls `getModel` and thus `getXliffFilenameAndPath` which again loops over the locale chain.

Sounds like a lot of looping to me… the again, it could very well be a negligible amount of time spent there. Any numbers on this, @ComiR or @albe?

**Comment by albe** [comment]
Good catch, but I think even if performance weren't a problem, there is a functional problem. The translator deals with choosing the locale to use if none is specified, while the providers always expect a valid locale - but the Xliff Provider might return a file that does not match that locale, because `getLocaleChain` will for example use configured fallbacks or even the default locale.
So IMO the `I18n\Service::getXliffFilenameAndPath` should not deal with the locale chain at all. Since it's only used in XliffTranslationProvider it should not break anything. Alternatively, for maximum b/c, it should have a $strict parameter like `I18n\Service::getLocalizedFilename` which should be set to true when calling from XliffTranslationProvider.

**Comment by dfeyer** [comment]
This change is breaking so should target master ... or maybe only the next major ?

**Comment by albe** [comment]
Is this really breaking? I mean it will possibly return translations from the chain where it wouldn't return anything before, but is this considered *breaking*? Just curious

**Comment by jonnitto** [comment]
Any progress on this? Is this something for the new release?

**Comment by ComiR** [comment]
Closing in favor of #1451.
Please continue discussion there.

**Pull request closed without merging**
