### PR TITLE
BUGFIX: Adjust to Php 83 `get_parent_class` deprecation

### PR DESCRIPTION
**Pull request by mhsdesign**
see https://www.php.net/manual/en/function.get-parent-class.php

**Upgrade instructions**

**Review instructions**

**Checklist**

- [ ] Code follows the PSR-2 coding style
- [ ] Tests have been created, run and adjusted as needed
- [ ] The PR is created against the [lowest maintained branch](https://www.neos.io/features/release-roadmap.html)
- [ ] Reviewer - PR Title is brief but complete and starts with `FEATURE|TASK|BUGFIX`
- [ ] Reviewer - The first section explains the change briefly for change-logs
- [ ] Reviewer - Breaking Changes are marked with `!!!` and have upgrade-instructions

### CODE REVIEW

**Comment by mhsdesign** [comment]
Must have gone missing while upmerging https://github.com/neos/flow-development-collection/pull/3032 i guess

**Comment by lorenzulrich** [comment]
@mhsdesign I suspect that this change has regressions. In https://github.com/neos/flow-development-collection/pull/3406, I backported this change to 8.3 and applied it as a patch in an installation.

Now, when I call an own repository that **extends** a Neos repository and call a method that creates a query, I get this error:

```bash
Call to a member function createQueryForType() on null

  Type: Error
  File: Packages/Framework/Neos.Flow/Classes/Persistence/Repository.php
  Line: 137
```

So somehow DI fails in this case. I suspect it is because PHP <8.3 `get_parent_class()` is not identical to PHP 8.3 `get_parent_class($this)`.

https://www.php.net/manual/en/function.get-parent-class.php#refsect1-function.get-parent-class-changelog

**Comment by lorenzulrich** [comment]
It seems that using `method_exists(parent::class` as mentioned [here](https://php.watch/versions/8.3/get_class-get_parent_class-parameterless-deprecated#get_parent_class-replacement) seems to work in my situation. However I'd be surprised if that part of Flow wasn't covered by a test.

**Comment by kdambekalns** [comment]
As mentioned in the post you linked, `parent::class` fails without a parent and the proper replacement would be `get_parent_class($this)`. Also the PHP documentation says:

>  previously, calling this function inside a class returned the name of that class. 

And inside a class, `$this` is, well, "that class". Also, https://3v4l.org/6TtkP shows no difference for PHP < 8.3

**Comment by kitsunet** [comment]
Given that this here happens in a proxy class we can safely assume a parent::class cannot fail?!

**Comment by kdambekalns** [comment]
Yep, in this case, true. I was more trying to prove that the change as a reason for the "mthod call on null" seems… strange?!

**Pull request merged**
