### PR TITLE
BUGFIX: Uri must not be constructed with empty string

### LINKED ISSUE #2473: UriConstraints should make sure the Uri path starts with a slash
See https://github.com/guzzle/psr7/blob/1.4.1/src/Uri.php#L704

### PR DESCRIPTION
**Pull request by kdambekalns**
Fixes #2473

### CODE REVIEW

**Review by mficzel — APPROVED** [review]
Fine by reading

**Review by albe — APPROVED** [review]
Reads good, almost too easy

**Comment by albe** [comment]
That was indeed "too easy" and doesn't resolve #2473 - see explanation at https://github.com/neos/flow-development-collection/pull/2501#issuecomment-1087385623

**Comment by kdambekalns** [comment]
Hm. Should this be reverted then, as it was completely useless?

**Pull request merged**
