### PR TITLE
TASK: Raise minimum PHP version to 7.3

### PR DESCRIPTION
**Pull request by albe**
Require PHP 7.3 in composer.json

### CODE REVIEW

**Comment by albe** [comment]
🤦‍♂️

**Review by kdambekalns — CHANGES_REQUESTED** [review]
This is not enough, at least it **must** be raised in `Neos.Flow/composer.json`, too. But **should** be done in `Neos.*/composer.json`, for consistency - then we can rely on that version in all packages…

**Comment by albe** [comment]
Needed to correct the commit message anyway, so rewrite history ftw

**Review by kdambekalns — APPROVED** [review]
👏

**Pull request merged**
