### PR TITLE
TASK: Improve functional test persistence tearDown()

### PR DESCRIPTION
**Pull request by kdambekalns**
This adds `forgetInstance` calls to the `tearDown()` in the Flow
`FunctionalTestCase` that avoid side effects between tests. One sympto this
fixes is failing tests caused by "The entity manager is closed" when a
preceeding test produced an exception during `persistAll()`.

### CODE REVIEW

**Comment by kdambekalns** [comment]
What I'd love to have feedback/input on:

- can we remove more/other cleanup with this?
- should this go into this, earlier or the master branch only?
- why didn't we do it like this from the start?

**Comment by kdambekalns** [comment]
Huh, failures… Two things may be needed: One of the failures might actually rely on the EntityManager not being cleaned up properly. And the "too many connections" could be caused by a new connection per test, but existing ones are not properly closed because the "reset" is a bit too simplistic.

**Comment by kitsunet** [comment]
Sounds like a good idea to me. I guess closing the connection is a good idea though. Maybe it was just not done for performance reasons?

**Comment by kdambekalns** [comment]
I assume no closing was needed since the EM was not thrown away, and thus no new connections were created…

**Comment by kitsunet** [comment]
Right, but with this change it's needed or do I miss something?

**Comment by kdambekalns** [comment]
It seems as if it's needed, yes. :)

**Comment by albe** [comment]
> - can we remove more/other cleanup with this?

I couldn't find anything on first look. All persistenceManager clearing is done within tests to simulate two requests.

> - should this go into this, earlier or the master branch only?

IMO earlier, cleaning up properly is a bugfix.

> - why didn't we do it like this from the start?

No clue.

**Comment by Torsten85** [comment]
Correct me if I'm wrong but a lot of objects hold a reference to the `PersistenceManager` and relying on the singleton pattern to ensure that all references pointing to the same object. "Forgetting" the `PersistenceManager` (or any singleton) would mean, that in every test a new instance would be created and you end up with multiple PersistenceManagers. Due to the statefulness this could lead to a lot of other problems.

**Comment by albe** [comment]
Stumbling upon this again and I think it's still a good thing to get more robust functional tests. Regarding the valid concerns Torsten raised:
Indeed that would be an issue and break more things than this solves. The case here basically is some Singleton that has the PersistenceManager/EntityManager injected, and hence ends up holding a reference to another instance than the one supposed for the current test run.

So I think we need to be more radical here and do an `forgetAll`. That way only custom Singletons that themself hold a reference to one of the Flow Singletons would break, but then again, this is really a bad use case that I have no issue with.

Only downside is the (highly?) decreased performance for the functional tests.

**Pull request closed without merging**
