### PR TITLE
[BUGFIX] Fix PHP 5.3 compatibility issues

### PR DESCRIPTION
**Pull request by kdambekalns**
The 2.3 branch should be compatible to PHP 5.3, but since we did not have automated
testing in place on that version of PHP, some incompatibilties have crept in.

This fixes those issues and enables the unit and functional tests to be run on PHP 5.3
on Travis CI.

Also the Behat tests for Flow are run with this, since there is no reason they shouldn't.

### CODE REVIEW

**Comment by kdambekalns** [comment]
This depends on https://github.com/neos/flow-development-distribution/pull/3

**Comment by kitsunet** [comment]
aren't the traits used in neos? respectively the typo3cr behat tests?

**Comment by kitsunet** [comment]
yep see `/Volumes/CaseSensitive/Work/PhpstormProjects/neos-dev-master/Packages/Neos/TYPO3.TYPO3CR/Tests/Behavior/Features/Bootstrap/FeatureContext.php`
which doesn't even have a namespace....

**Comment by kdambekalns** [comment]
And the counterpart for Neos: https://github.com/neos/neos-development-collection/pull/236 /cc @kitsunet

**Comment by kitsunet** [comment]
Great work :) thanksa lot

**Comment by kdambekalns** [comment]
Ok, looks good to me now. _sigh_

**Pull request merged**
