### PR TITLE
TASK: Relax psr cache constraints

### LINKED ISSUE #2804: Dependency on psr/cache ^3.0 is too "eager"
It leads to an incompatibility with `google/auth`… in turn breaking the dependency chain if you need that (for `google/apiclient`, which is needed for e.g. `flowpack/googleapiclient`).

_Originally posted by @kdambekalns in https://github.com/neos/flow-development-collection/issues/2789#issuecomment-1083319800_

### PR DESCRIPTION
**Pull request by kdambekalns**
Fixes #2804

### CODE REVIEW

**Comment by kdambekalns** [comment]
I checked, and yes, one can `provide` multiple versions of something…

**Review by mficzel — APPROVED** [review]
Fine by reading. If the tests get green (especially with deps lowest) everything is fine.

**Review by albe — APPROVED** [review]

**Comment by mficzel** [comment]
@albe wonder aswell, there has been one if remember correctly

**Comment by albe** [comment]
See https://github.com/neos/flow-development-collection/pull/2806

**Comment by kdambekalns** [comment]
Ok, this time with a lowest-dependencies check. 🤞

**Pull request merged**
