### PR TITLE
BUGFIX: Use missing method EnvironmentConfiguration::getApplicationContext

### PR DESCRIPTION
**Pull request by dfeyer**

### CODE REVIEW

**Comment by aertmann** [comment]
this would mean that the caches are shared between the contexts right? that would be really bad.. why not get the context from Bootstrap instead?

**Comment by kitsunet** [comment]
@aertmann this is the splitted cache package, it shoudl know nothing about flow. The application identifier needs to contain everything ot uniquely identify the application, so in our case also the context, which in turn is configured in Flows CacheManager or Factory.

**Comment by aertmann** [comment]
@kitsunet: okay makes sense, but does it? that's the important part

**Comment by aertmann** [comment]
nvm it does, https://github.com/neos/flow-development-collection/blob/master/Neos.Flow/Classes/Cache/Backend/BackendCompatibilityTrait.php#L48

**Pull request merged**
