### PR TITLE
Add PDO cache driverOptions

### PR DESCRIPTION
**Pull request by pagani-BETTERHOMES**
resolved: https://github.com/neos/flow-development-collection/issues/3157

### CODE REVIEW

**Review by dlubitz — APPROVED** [review]
Thank you for your contribution. This looks good to me.

**Comment by dlubitz** [comment]
If we consider this as a bugfix we could think about a merge into 7.3. 🤔

**Comment by mhsdesign** [comment]
yes ;) Please target 7.3 (you can easily rebase this locally via `git rebase origin/7.3` and then change the base branch in github ^^

Bugfixes go to 73 
and Features to 83 :D

**Comment by kdambekalns** [comment]
> and Features to 83 :D

To 9.0, strictly speaking…

**Comment by kdambekalns** [comment]
Hi @pagani-BETTERHOMES – will you rebase this onto 7.3? Otherwise I'll make a mental note to do it next week…

**Comment by pagani-BETTERHOMES** [comment]
> Hi @pagani-BETTERHOMES – will you rebase this onto 7.3? Otherwise I'll make a mental note to do it next week…

Hi @kdambekalns, I'd be happy if you could do this, I won't be able to do it before mid October.

**Comment by kdambekalns** [comment]
Replaced by #3184

**Pull request closed without merging**
