### PR TITLE
Update: ignore disabled authentication providers

### LINKED ISSUE #2606: Allow to disable authentication providers
### Description
Right now, it is not possible to disable authentication providers that have been introduced in other packages (e.g. third-party packages). 

### Steps to Reproduce
1. Go to Neos:Flow:security:authentication:providers
2. Disable the desired provider by 'TheProvider': ~
3. reload auth request

#### Expected behavior

No error should occure 

#### Actual behavior

Error Message: The configured authentication provider "TheProvider" needs a "provider" option!

### Affected Versions

Neos 5.3 LTS and above

### PR DESCRIPTION
**Pull request by davidspiola**
**What I did**
Ignore null providers in the provider factory

**How I did it**
Ignore null providers in TokenAndProviderFactory::buildProvidersAndTokensFromConfiguration foreach loop

**How to verify it**
Set `Neos.Neos:Backend` provider to `null`, `~` or `false` in order to disable it and check for php errors on next login request

**Checklist**

- [x] Code follows the PSR-2 coding style
- [ ] Tests have been created, run and adjusted as needed
- [x] The PR is created against the [lowest maintained branch](https://www.neos.io/features/release-roadmap.html)

Fix #2606

### CODE REVIEW

**Review by albe — APPROVED** [review]

**Comment by albe** [comment]
Ah wait, just noticed this targets 5.3, but should be 6.3 by now. 5.3 is security-only

**Comment by markusguenther** [comment]
> Ah wait, just noticed this targets 5.3, but should be 6.3 by now. 5.3 is security-only

Guess that was just the confusion about the non synced version numbers :D

**Comment by davidspiola** [comment]
ahh..  I accidentally merged it 🥺. Its' not my job! Is that a problem?

**Comment by markusguenther** [comment]
Ah that's the way to go 🤣

**Comment by albe** [comment]
> ahh.. I accidentally merged it 🥺. Its' not my job! Is that a problem?

Should be good AFAIS. Had positive review already and was retargeted so all good.

**Pull request merged**
