### PR TITLE
TASK: Change version constraints for Neos packages to self.version

### PR DESCRIPTION
**Pull request by dlubitz**

### CODE REVIEW

**Review by ahaeslich — DISMISSED** [review]

**Comment by kitsunet** [comment]
Mmm, now I wonder, I thought this was _after_ we supposedly fixed the release scripts. I guess I'll have a look at that again tomorrow.

https://github.com/neos/flow-development-collection/commit/702e93262131319cd72bef01dfad0739f71ade0d

**Comment by ahaeslich** [comment]
> Mmm, now I wonder, I thought this was _after_ we supposedly fixed the release scripts. I guess I'll have a look at that again tomorrow.
> 
> [702e932](https://github.com/neos/flow-development-collection/commit/702e93262131319cd72bef01dfad0739f71ade0d)

I can't remember that we checked the dependcies here during our first beta release for Neos 9. We did change something for the neos-development-collection. Maybe we simply missed it?

**Comment by ahaeslich** [comment]
@kitsunet oh didn't this happen because we upmerged https://github.com/neos/flow-development-distribution/pull/85 into the 9.0 branch AFTER we released the first beta?

I guess simply updating all 4 files to using "self.version" should fix it again.

**Comment by dlubitz** [comment]
I also changed the version constraints in the other files regarding to https://github.com/neos/flow-development-collection/commit/702e93262131319cd72bef01dfad0739f71ade0d

**Comment by kitsunet** [comment]
I'll merge this later today, but definitely want to have a look at the release scripts first, nothing happens there until we do a next beta but still, I am pretty sure this wasn't an upmerge or anything but the scripts.

**Comment by kitsunet** [comment]
Ah, here we go, the upmerges came only beginning of december, so at the point of be beta it wasn't upmerged. All good I guess... https://github.com/neos/flow-development-distribution/commits/9.0/Build/set-dependencies.sh

**Review by kitsunet — APPROVED** [review]

**Pull request merged**
