### PR TITLE
BUGFIX: Add translation for error message (string length)

### PR DESCRIPTION
**Pull request by kdambekalns**
The translation is broken in 3.0 and up, even though it appears to be
correctly translated in Crowdin.

This is try to fix this.

### CODE REVIEW

**Comment by kdambekalns** [comment]
By analyzing using my project knowledge, I identifier @aertmann, @kitsunet and @albe to be potential reviewers

**Comment by albe** [comment]
The new kdambekalns-mentionbot works pretty well ;)

**Comment by aertmann** [comment]
it's a general problem, not just with German.. probably due to the identifier containing `[]`

thus it will probably just break next time it's overridden and still broken with all other languages

@kdambekalns is there anything we can do to fix it or do we need to open an issue with Crowdin?

**Comment by kdambekalns** [comment]
Hm, that sounds like an issue with CrowdIn then. Also I found http://crowdin.betaeasy.com/thread/4164 which sound slightly similar. I contacted the CrowdIn support… let's see what happens.

**Comment by kdambekalns** [comment]
So I got a reply already:

> I assume the issue is caused on our side, somehow it's related with plural forms.
> 
> The task is already created and we will do our best to find the solution this week. Due to holidays here in Ukraine, our developers can review this bug not earlier than Wednesday this week, sorry for a little delay.

**Comment by kdambekalns** [comment]
Got this in the mail today:

> I want to inform you that we have already fixed the issue with the exported XLIFF files and pushed the fix to the production.
> It would be great if you can confirm that everything works fine!

I'll check the generated XLIFF files…

**Comment by kdambekalns** [comment]
Their fix doesn't change anything. I'll let them know, let's hope for more feedback.

**Comment by kdambekalns** [comment]
Ok, they got back to me and after updating the english (source) XLIFF file, the plural form shows up in the translation screen and is built correctly. So we can close this. 🎉 

plural-forms-crowdin

**Comment by kdambekalns** [comment]
FYI: We have one more plural in Neos "Modules.xlf", that still doesn't translate correctly (is not showing up at all in the Crowdin UI). I got in touch with their support…

**Pull request closed without merging**
