### PR TITLE
BUGFIX: Allow objects to be serialized twice without loosing their relations to persisted properties

### PR DESCRIPTION
**Pull request by fcool**
This should solve the issue described in #2009

### CODE REVIEW

**Comment by albe** [comment]
wait, needs to target 5.3...

**Comment by fcool** [comment]
Is there a a way to modify this pull request? Or is it as simple as create a new one?

**Comment by albe** [comment]
ah, damn travis... why can't you just rebuild correctly after base branch change?

**Comment by fcool** [comment]
One thing, which might be a reason to keep it in 4.3 is, that this way it might get possible to remove objects from the session. Which might have impacts on the authentication processes - even if I can only think of "logging somebody out" and not gaining additional privileges. Some kind of "logout CSRF" ;)

**Comment by albe** [comment]
Another test with /rebase

**Comment by albe** [comment]
If this was a security issue, we should probably handle it a bit differently ;) I'd rather target 5.3 with this

**Pull request closed without merging**
