### PR TITLE
TASK: Do not instantiate all available TypeConverters

### PR DESCRIPTION
**Pull request by kdambekalns**
Previously the ``PropertyMapper`` would instantiate all available
TypeConverter implementations to build a map of possible sources
and targets. This is now done during compiletime so that only
instances of TypeConverters are created that have the required
source and target types.

NEOS-1288 #close

### CODE REVIEW

**Comment by kdambekalns** [comment]
@kitsunet did you forget to commit some part here?

**Comment by kitsunet** [comment]
yep seems pretty much so. I will think about it when my head is clear again. I am sure I can reproduce what I originally had there.

**Comment by kdambekalns** [comment]
@kitsunet Could you have a look at this one (again)? Thanks!

**Comment by kitsunet** [comment]
https://github.com/neos/flow-development-collection/pull/318
Is a working replacement that improves things in production.

**Pull request closed without merging**
