### PR TITLE
FEATURE: Extend AuthenticationManagerInterface with getter for providers

### PR DESCRIPTION
**Pull request by dlubitz**
Adds a new getter method to the AuthenticationManagerInterface, that has to return all provided authentication providers.

### CODE REVIEW

**Comment by dlubitz** [comment]
screen

Unattractive is at the moment the TYPO3SetupProvider. Maybe it make sence to filter providers by provider type `PersistedUsernamePasswordProvider`?

**Comment by gerhard-boden** [comment]
please add a prefix to commit message "FEATURE: " before the merge.  Aside from that, :+1:

**Comment by kdambekalns** [comment]
Out of curiosity: what is the use case?

**Comment by dlubitz** [comment]
@kdambekalns E.g to provide the possibility to create accounts with different auth providers in Neos backend. For example the FrontendLogin:Frontend of Flowpack.
see https://github.com/neos/neos-development-collection/pull/612

**Comment by kdambekalns** [comment]
Ah, ok. Thanks, that was the missing link…

**Pull request merged**
