### PR TITLE
fix log file size

### PR DESCRIPTION
**Pull request by rkrahnen**
Hey guys, it's just a small fix for the log file size of the `i18nLogger` as it seems to me like there is just a zero missing.

### CODE REVIEW

**Comment by albe** [comment]
Ah! Very good catch, indeed that is off! Would be good to fix this in 5.3 though, as it's clearly a BUG:
https://github.com/neos/flow-development-collection/blob/5.3/Neos.Flow/Configuration/Settings.Log.yaml#L47

**Comment by rkrahnen** [comment]
Will you do this or should I create a new pull request for the 5.3 branch?

**Comment by albe** [comment]
Needs a new PR, so would be cool if you could do this :) Thanks!

**Comment by albe** [comment]
friendly ping @rkrahnen :)

**Comment by rkrahnen** [comment]
I will do the new PR today evening, sorry for the delay!

**Pull request closed without merging**
