### PR TITLE
BUGFIX: Fix ObjectAccessorNode::getPropertyPath for is/has access in PHP7

### PR DESCRIPTION
**Pull request by kdambekalns**
This fixes the try/catch for undefined Fluid variables which start with "is" or "has".
Currently, exceptions here are not being caught because an `\Error` is being thrown.
Since non-callable method call should not be attempted in the first place, this change
adds a is_callable check. Therefore a try/catch block is no longer necessary, as any exception thrown inside the callable method should bubble up.

Specific example: a fluid section/partial with an optional argument called "isSomething"

- if rendered while defining isSomething in the arguments, there's no problem
- if rendered without isSomething in the arguments (implicit falsy), we then get
  `Call to undefined method TYPO3\Fluid\Core\ViewHelper\TemplateVariableContainer::isSomething()`

Related to: #108, #343, #348, whythecode/flow-development-collection#1

### CODE REVIEW

**Comment by kdambekalns** [comment]
@albe Your test failed because `null !== ''` - did you run the test after you wrote it? Because I wonder if this is actually correct (returning `null`) or if `render()` should return an empty string here…

**Comment by albe** [comment]
Yep, and it passed. Rendering a view should always return a string, even if it only consists of a single variable that resolves to null, no? IIRC I even had it check for null beforehand and that failed. I'll check again tomorrow, maybe I overlooked something or some weird cache misbehaviour made it pass after that null fail before?

**Comment by albe** [comment]
After a quick look it seems that indeed a View render might indeed return null. ParsingState::render is documented to return a string, but the called RootNode::evaluate resp. AbstractNode::evaluateChildNodes can possibly return null (if the tree is empty for example or, as in this case, only consists of a single node evaluating to null).
Couldn't find a test at first look that covers this behaviour, so maybe this is unintended. Do you know anything maybe @bwaidelich?

**Comment by bwaidelich** [comment]
Thanks everybody for fixing this. I'll prepare a PR for master that moves the logic to `ObjectAccess` - that'll simplify & unify things and should be able to keep the new tests as is.

> After a quick look it seems that a View render might indeed return null

Right.. `AbstractTemplateView::render()` internally calls `NodeInterface::evaluate()` with an unknown return type. The reason is that e.g. a ViewHelper node can return anything you want it to.
I'd suggest to cast the result to a `string` in the View implementation. Or do you see any problems with that, @skurfuerst ?

**Comment by whythecode** [comment]
thx, all!

**Comment by skurfuerst** [comment]
@bwaidelich agreed, that should work I think if it is casted inside the *View*

**Pull request merged**
