### PR TITLE
TASK: Wrong namespace configuration for some package

### PR DESCRIPTION
**Pull request by dfeyer**

### CODE REVIEW

**Comment by dfeyer** [comment]
:+1:

**Comment by kitsunet** [comment]
Wait, did you fix that by hand?

**Comment by dfeyer** [comment]
:( wrong file

**Comment by kitsunet** [comment]
;)

**Comment by dfeyer** [comment]
Now it should be OK ;)

**Comment by kitsunet** [comment]
:+1:

**Pull request merged**
