### PR TITLE
FEATURE: Allow nodeType definitions in subfolders

### PR DESCRIPTION
**Pull request by hphoeksma**
NodeType definitions can be nested inside subdirectories of the Configuration folder, i.e.:

```
- Configurations
  - Folder
    - NodeType.Definition.yaml
  - ...
```
This can be useful when dealing with loads of nodetype definitions.

**What I did**

**How I did it**

**How to verify it**

**Checklist**

- [ ] Code follows the PSR-2 coding style
- [ ] Tests have been created, run and adjusted as needed
- [ ] The PR is created against the [lowest maintained branch](https://www.neos.io/features/release-roadmap.html)

### CODE REVIEW

**Comment by hphoeksma** [comment]
I have noticed some caching issues with this change that I don't know how to tackle. That is: when clearing cache and running a check on available nodetypes it all works well, a second time however only the first layer (not the subdirs) are loaded. Tried to wrap my head around how that is setup, but could not figure out why it ain't working.

**Comment by bwaidelich** [comment]
Thanks for this contribution!
Unfortunately the topic is a bit more complicated (as you already figured out).
With https://github.com/neos/neos-development-collection/issues/3000 and especially #2449 we are working on a greater refactoring. (Unfortunately this is stuck right now since Github checks are currently broken due to #2479)

**Comment by hphoeksma** [comment]
@bwaidelich ghehe... thanks for pointing to those PR's. Guess we are stuck with 2900+ nodetypes then... 😢

**Comment by bwaidelich** [comment]
> Guess we are stuck with 2900+ nodetypes then

you can definitely speed up the process by testing / reviewing the other PRs. I'm sure that the doctrine issue will be resolved very soon

**Comment by bwaidelich** [comment]
BTW: That is the PR that will allow NodeTypes to be defined in subfolders: https://github.com/neos/neos-development-collection/pull/3332

**Comment by bwaidelich** [comment]
Closing in favor of #2449 and https://github.com/neos/neos-development-collection/pull/3332 – thanks for your contribution!

**Pull request closed without merging**
