### PR TITLE
TASK: Update styling of var_dump and exception messages

### PR DESCRIPTION
**Pull request by kitsunet**
This adapts the styling of the ``\Neos\Flow\var_dump`` and
debug exception handler to match our current CI more.
Additionally overhauls the markup of the debug exception handler
to a more semantic structure and without inline styles.

### CODE REVIEW

**Comment by kitsunet** [comment]
screen shot 2016-12-04 at 14 38 59
screen shot 2016-12-04 at 14 39 23

**Comment by kitsunet** [comment]
Note: The shown exception is obviously made up, I added it to the NodeController to have a reliable way to test this ;)

**Comment by aertmann** [comment]
me like, awesome @kitsunet!

**Comment by kitsunet** [comment]
<3

**Pull request merged**
