### PR TITLE
TASK: The RenderingContext no longer has a view argument

### PR DESCRIPTION
**Pull request by kdambekalns**

### CODE REVIEW

**Review by fcool — APPROVED** [review]

**Review by kdambekalns — COMMENTED** [review]
Ok, see https://github.com/neos/flow-development-collection/pull/2546 - this needs to go into 7.2 with a bumped Fluid dependency (2.7.0)…

**Comment by albe** [comment]
☝️

**Comment by kdambekalns** [comment]
Here we go: Based on master and including a version bump for `typo3fluid/fluid` to `^2.7.0`…

**Comment by kdambekalns** [comment]
The build failure is caused by Guzzle vs Behat, see #2547

**Comment by kdambekalns** [comment]
Ping…

**Review by fcool — APPROVED** [review]

**Comment by albe** [comment]
Post-merge 👍

**Pull request merged**
