### PR TITLE
TASK: Psalm failures create a new branch with baseline update

### PR DESCRIPTION
**Pull request by albe**
TODO: Maybe only execute when the last commit was a merge commit and then directly push to the branch?

### CODE REVIEW

**Comment by albe** [comment]
Okay, I think I'm not gonna get this working so easily... currently not getting through the GH authentication for pushing the changes

**Comment by albe** [comment]
Yes, basically. Just didn't want to create a copy of the styleCI bot, but maybe that's easier after all? Someone got experience with GH bots?

**Comment by kdambekalns** [comment]
> Someone got experience with GH bots? 

Not me, sorry…

**Comment by albe** [comment]
Maybe the "checks API" is another option: https://developer.github.com/apps/quickstart-guides/creating-ci-tests-with-the-checks-api/#step-26-automatically-fixing-rubocop-errors?
Also thought about creating a GH action for psalm - not sure if that solves the authentication problem.

GH has too many APIs...

**Comment by albe** [comment]
Closing in favor of #2413

**Pull request closed without merging**
