### PR TITLE
FEATURE: Add debug output for \ArrayObject instances

### PR DESCRIPTION
**Pull request by vjanoch**

### CODE REVIEW

**Comment by kdambekalns** [comment]
:+1: by reading

**Comment by kitsunet** [comment]
:+1:

**Comment by dfeyer** [comment]
:+1:

**Comment by aertmann** [comment]
any reason not to support ``\ArrayIterator`` as well? https://github.com/doctrine/common/blob/master/lib/Doctrine/Common/Util/Debug.php#L125

**Comment by kitsunet** [comment]
Merging this to stall not for too long, definitely an improvement. We can add `\ArrayIterator` support at any point.

**Pull request merged**
