### PR TITLE
[BUGFIX] Use CollectionInterface in resource management

### PR DESCRIPTION
**Pull request by hhoechtl**
Currently some methods use the Collection class instead of the
CollectionInterface.

### CODE REVIEW

**Comment by aertmann** [comment]
:+1:

**Comment by robertlemke** [comment]
:+1:

**Comment by bwaidelich** [comment]
what's wrong with this one? wrong branch?

**Comment by aertmann** [comment]
Needs to be rebased

**Comment by hhoechtl** [comment]
Done

**Comment by aertmann** [comment]
Closed and reopened to get tests running

**Pull request merged**
