### PR TITLE
TASK: Improve code readability

### PR DESCRIPTION
**Pull request by albe**
This change avoids needless `else` statements and tries to minimize the amount of
 context required to keep in mind by reducing deep indentations.

### CODE REVIEW

**Comment by kitsunet** [comment]
OMG, generally <3
Just this will break any single PR afterwards, so we need to find a good time to merge this.

**Comment by albe** [comment]
Yep, also thought about that after pushing. Also will make upmerges more complicate... maybe retarget lower?

**Comment by albe** [comment]
PS: kudos to @ocramius for making me take a look and walk through all that with his "Birthday wish" ;)

**Comment by kitsunet** [comment]
Nah, for targeting lower I will it'S too big a change... But I mean, we have to chnage namespaces, move files etc. anyway. So upmerges will be a mess afterwards regardless.

**Comment by albe** [comment]
True

**Comment by kdambekalns** [comment]
So, this has a ton of merge conflicts now… anyone up for rebasing or merging in master? Do we consider it worth the effort?

**Comment by Ocramius** [comment]
Easier to just re-run the CS rules against latest master.

**Comment by albe** [comment]
If we agree to merge afterwards I'm willing to go the round again. As stated, it will cause merge conflicts in pretty much every other PR once merged, so we need to agree on the merge time first.

And I'd say a clear "yes!" for considering it worth the effort :)

**Comment by albe** [comment]
So as discussed in https://discuss.neos.io/t/bigger-code-cleanup-effort/1983/3 I will restart the effort in several small PRs. Closing this now.

**Pull request closed without merging**
