### PR TITLE
BUGFIX: Add behat @BeforeSuite and @AfterSuite to ignored annotation tags

### PR DESCRIPTION
**Pull request by erickloss**
**What I did**
This adds the missing behat annotations to ignored tags, so behat tests using those hooks can be reflected.

**How to verify it**
This is an example of the error that occurs currently when `@BeforeSuite` or `@AfterSuite` is used in any Behat Step class.
image
see also https://github.com/sandstorm/Sandstorm.E2ETestTools/pull/6
This can also be avoided when classes containing those annotations are *not reflected*, meaning if they are outside the psr classes directory.
When they are *inside* psr class directories, an error is thrown (see screenshot)

### CODE REVIEW

**Review by sorenmalling — APPROVED** [review]

**Review by mhsdesign — COMMENTED** [review]
Isnt this a bugfix and should targed `6.3`?

(then needs to be rebased, changing the branch in the UI doesnt work alone)

**Review by mhsdesign — APPROVED** [review]

**Comment by albe** [comment]
Yes, let's get this into 6.3 please. @erickloss can you rebase this PR onto 6.3 or create a new PR please?

**Comment by erickloss** [comment]
@albe done :) cheers dude

**Review by albe — APPROVED** [review]

**Comment by albe** [comment]
Thanks a lot @erickloss and congrats on your first contribution :)

**Comment by erickloss** [comment]
> Thanks a lot @erickloss and congrats on your first contribution :)
it was about time <3

**Pull request merged**
