### PR TITLE
TASK: Add PHP process debug info in logged exception

### PR DESCRIPTION
**Pull request by dfeyer**
This change add the current PHP process PID, script Inode and
current user information (UID, GID, Username) when Flow log an
exception.

### CODE REVIEW

**Comment by dfeyer** [comment]
Why StyleCI failed ... on file not touched by the PR :(

Can anyone on Windows test this PR, in the logged exception, after the HTTP RESPONSE, you should see something like:

    PHP PROCESS:
    Inode: 36677501
    PID: 58999
    UID: 501
    GID: 20
    User: dfeyer

**Comment by dfeyer** [comment]
> Why StyleCI failed ... on file not touched by the PR :(

My master was far far away in the past

**Comment by dfeyer** [comment]
:+1:

**Comment by kitsunet** [comment]
:+1:

**Pull request merged**
