### PR TITLE
TASK: Remove Bootstrap::MINIMUM_PHP_VERSION

### PR DESCRIPTION
**Pull request by mhsdesign**
We declare these dependencies in composer and it should not be necessary to validate them at runtime.

**Upgrade instructions**

**Review instructions**

**Checklist**

- [ ] Code follows the PSR-2 coding style
- [ ] Tests have been created, run and adjusted as needed
- [ ] The PR is created against the [lowest maintained branch](https://www.neos.io/features/release-roadmap.html)
- [ ] Reviewer - PR Title is brief but complete and starts with `FEATURE|TASK|BUGFIX`
- [ ] Reviewer - The first section explains the change briefly for change-logs
- [ ] Reviewer - Breaking Changes are marked with `!!!` and have upgrade-instructions

### CODE REVIEW

**Review by kdambekalns — APPROVED** [review]
Reasonable line of thought…

**Comment by kdambekalns** [comment]
Ideas for a follow up:

- remove the check for "older than Windows Vista or Windows Server 2008"
- replace check for `Reflection` by a composer requirement

**Review by kitsunet — APPROVED** [review]

**Comment by mhsdesign** [comment]
upsi the tests were still red 🤯

**Comment by kitsunet** [comment]
hahhaha UUUPS

**Comment by kitsunet** [comment]
I pushed a fix to 9.0.

https://github.com/neos/flow-development-collection/actions/runs/7085996367

**Comment by mhsdesign** [comment]
Thänks for that https://github.com/neos/flow-development-collection/commit/401c861d354aa2b4d25ba5797d28e510104d3942 ;)

(i just couldnt decide which constant to use ^^)

**Pull request merged**
