### PR TITLE
TASK: Replace TYPO3 with Neos (excluding tests)

### PR DESCRIPTION
**Pull request by ComiR**
Only in the following paths:
* Classes/*
* Configuration/*
* Resources/*
* Scripts/*

Especially the tests aren't migrated yet.

### CODE REVIEW

**Comment by gerhard-boden** [comment]
So in combination with this the tests should turn green, right?
https://github.com/neos/flow-development-collection/pull/839

**Comment by robertlemke** [comment]
@gerhard-boden TBDSUAE.

**Comment by robertlemke** [comment]
(* thanks, but don't start using acronyms everywhere: https://mannerofspeaking.org/2015/12/17/acronyms-can-seriously-suck/ :))

**Comment by robertlemke** [comment]
Related to #823

**Comment by gerhard-boden** [comment]
@robertlemke SWSDT (sorry, will stop doing that) 😄

**Pull request merged**
