### PR TITLE
FEATURE: Resources can be published with relative symlinks

### PR DESCRIPTION
**Pull request by kitsunet**
Adds a new option to the ``FileSystemSymlinkTarget`` named
``relativeSymlinks`` which will calculate a relative path from
source to target and symlink to that relative path instead of an
absolute path.

### CODE REVIEW

**Comment by kitsunet** [comment]
Moved over from Gerrit 30519, needs good testing...

**Comment by kdambekalns** [comment]
@kitsunet so this is ready but needs thorough testing, right?

**Comment by kdambekalns** [comment]
Merged master into the branch…

**Comment by kitsunet** [comment]
Can we gt this done?

**Pull request merged**
