### PR TITLE
TASK: Update psalm baseline

### PR DESCRIPTION
**Pull request by markusguenther**

### CODE REVIEW

**Comment by kdambekalns** [comment]
@markusguenther Was this created by you, locally, or via the GH action?

**Comment by markusguenther** [comment]
Locally and it just works on my M1 machine ;)

**Comment by kdambekalns** [comment]
> @markusguenther Was this created by you, locally, or via the GH action?

I am asking, since the memcache additions point to no memcache being available, which should not be the case on GH

**Comment by markusguenther** [comment]
Yeah, it was more than expected :/

**Comment by kdambekalns** [comment]
Ok, what you can do, is create the update and manually remove the unexpected changes. 😎

**Pull request closed without merging**
