### PR TITLE
TASK: Adjust XSD domain to neos.io

### PR DESCRIPTION
**Pull request by markusguenther**
The XSD file generator still uses typo3.org instead of neos.io

Resolves: #1186

### CODE REVIEW

**Comment by kitsunet** [comment]
But that is a breaking change, right?

**Comment by markusguenther** [comment]
It depends ... but when you generate new xdd files... as uses the old one via typo3.org. You need to adjust your templates to get the new one.

So for upgrading people it is breaking. Ask myself why it is still TYPO3 ;)

**Comment by kdambekalns** [comment]
IMHO that is just a namespace URL. Just like `com.sun.java.…` - does it really make sense to change that? But making it an option sounds good, so the XSD can be generated for your own stuff and the be used alongside the default one…

Then again, for our "own Neos" viewhelpers, it should be probably be `neos.io` indeed.

Breaking: is this actually in widespread use?

**Comment by jonnitto** [comment]
Can we merge this one?

**Comment by markusguenther** [comment]
Think I will adjust it first to have the domain as parameter. Then you can have a own domain for you own package ViewHelpers for instance :)

**Comment by markusguenther** [comment]
Also added the parameter xsd-domain. So now everybody is able to generate xsd files with the own domain. If this parameter is not used or something in the URL is missing we are falling back to the neos.io URL.

**Comment by kitsunet** [comment]
I wanted to think this through since a while. Shouldn't we actually version those URIs? At least major versions, as breaking chnages to VHs may occur effectively making a separate "description" necessary?

And even though that's neither required nor expected it might be neat to actually provide a description of said VHs at the given URI at some point in the future, so we might want to choose the URI in a way that may easily allow us to do just that?

Some random thoughts I had earlier on this topic.

Also this is relevant:
https://discuss.neos.io/t/fluid-syntax-and-xmlns-namespaces/1903

**Pull request merged**
