### PR TITLE
FEATURE: webserver group membership check

### PR DESCRIPTION
**Pull request by wexi79**
File permission script checks that the command line user is a member of the webserver group

### CODE REVIEW

**Comment by dfeyer** [comment]
I agree that this can be a best practice and a good setup. But dependending on the hosting environnement ... not sure if it's possible to enforce this as a hard rule.

**Comment by wexi79** [comment]
Well, if the command line user is not a member of the webserver group, things will not work. Clearing the cache from the command line for example. So basically when running the script, you are supposed to give a group as the third option that the cli user is a member of.

**Comment by dfeyer** [comment]
@wexi79 I'm all in favor a being more strict/clear about our required setup ;)

But let's wait some more review before merging this one

**Comment by wexi79** [comment]
@dfeyer yeah, I havent' been abl to think about a situation when the group membership cannot be enforced but maybe someone can :)

**Comment by kdambekalns** [comment]
Hm. On my current setup  my user is not in the webserver group and things still work. Don't ask why, but… maybe make this a warning instead of a failure?

**Comment by wexi79** [comment]
@kdambekalns I'm still going to ask why :D 

Mainly I'm interested what kind of setup you have where your cli user IS NOT a member of the webserver group and things still work; how can the cli user remove cache/lock files from the Data directory if it is not the owner of those files or a member of the group? If the cli user and webserver user are the same, the user would still be a member of the webserver group also?

**Comment by kdambekalns** [comment]
Probably because of ACLs…

**Comment by wexi79** [comment]
Ah, you're right, then the check is not required. So maybe instead of displaying the warning, just move the check after the ACL support check? As if the script uses the file system method for setting permission and the cli user is not a member, you will get a broken setup (which is annoying).

**Comment by albe** [comment]
Needs a rebase, but what else is keeping this from merging, since it already got two approvals?

**Comment by albe** [comment]
Rebased. Would merge this evening if no one objects any more.

**Comment by albe** [comment]
So congrats to your first contribution @wexi79 and sorry it took so long :)

**Pull request merged**
