### PR TITLE
FEATURE: Make creating additional doctrine connections easier

### PR DESCRIPTION
**Pull request by kitsunet**
This is mainly a cleanup of the ``EntityManagerFactory`` and the
``FlowAnnotationDriver`` splitting both up into a base version to
be used as basis for custom doctrine connections and a Flow specific
version with the same class name as before. Additionally a lot of the
code was refactored into smaller methods to improve maintainability
and readability. No functional changes have been done to the code.

Entities using the ``BaseAnnotationDriver`` would not get the
``Persistent_Object_Identifier`` introduced which makes sense
for non Flow entities.

FLOW-391 #close

### CODE REVIEW

**Comment by kitsunet** [comment]
@kdambekalns I would love if you could take a look. This rotted away in Gerrit for ages already and I just redid it. Would be great to get it merged this time...

**Comment by albe** [comment]
Really not easy to review due to the large extraction of code. Maybe you can help a little: Were there any additional code changes in the extracted Base* classes or are those simply 1:1 copies of the old methods?

**Comment by kdambekalns** [comment]
@kitsunet, you said:
> Additionally a lot of the code was refactored into smaller methods to improve maintainability and readability.

Did you actually change the code in the annotation driver? As ugly as that may be, it was as close as possible to the Doctrine driver, making comparisons easier when adapting to newer Doctrine versions… So, please, don't refactor that one internally…

I'll actually test this later today…

**Comment by kdambekalns** [comment]
Oh, what about some documentation for this in the persistence chapter of the Flow manual?

**Comment by kitsunet** [comment]
Mmmm, I think I didn't change much code here but if the plan was to keep this similar to the doctrine driver we should probably just comment it in this way. I will take care of rebasing and looking after the thing including documentation.

**Comment by kdambekalns** [comment]
Well, I was the only one taking care of the driver for years, so… ;) Thanks!

**Comment by kdambekalns** [comment]
How do we proceed… The cleanup in the driver is counter-productive - @kitsunet could you take care?

**Comment by kitsunet** [comment]
Closing this, will create a new one from scratch without refactorings.

**Comment by MarkusRodler** [comment]
@kitsunet Can you provide a link to the new one? I can't find it.

**Comment by kitsunet** [comment]
Will create, not have created. Wil take a bit, has not really top prio for me right now.

**Pull request closed without merging**
