### PR TITLE
BUGFIX: ActionResponse contains negotiated media type as content-type

### PR DESCRIPTION
**Pull request by albe**
This sets the negotiated media type from the Controller in the `ActionResponse`.

### CODE REVIEW

**Comment by bwaidelich** [comment]
Can we figure out _where_ this was lost and add a test case to the `AbstractControllerTest`?

**Comment by albe** [comment]
I can not find any trace of that ever being in place, at least it's also not there in 4.3:
https://github.com/neos/flow-development-collection/blob/4.3/Neos.Flow/Classes/Mvc/Controller/AbstractController.php#L122-L128

I'm just wondering why that was never the case/never noticed. Guess because the webservers in use just do a very good job at providing sane defaults for the ContentType?

As to why this is targeted at 6.0: That's because the MVC response only carries the method to set a content-type since 6.0 and the PSR refactoring. Before the MVC response was a plain dumb container for a string content: https://github.com/neos/flow-development-collection/blob/4.3/Neos.Flow/Classes/Mvc/Response.php - so it was not even easily possible to set the Content-Type at this point.

I'll add a test case to https://github.com/neos/flow-development-collection/blob/6.0/Neos.Flow/Tests/Unit/Mvc/Controller/AbstractControllerTest.php to check the negotiated type is set in the response

**Comment by bwaidelich** [comment]
Thanks for double checking!

> I'm just wondering why that was never the case/never noticed. Guess because the webservers in use just do a very good job at providing sane defaults for the ContentType? 

Yes, probably.. weird.

I would suggest to make it a BUGFIX anyways (it can still be targeted for 6.0)

> I'll add a test case to https://github.com/neos/flow-development-collection/blob/6.0/Neos.Flow/Tests/Unit/Mvc/Controller/AbstractControllerTest.php to check the negotiated type is set in the response

Aweseome, thanks!

**Comment by bwaidelich** [comment]
..thinking about it once again: The negotiated content type refers to the _Request_ and it should not automatically set the response content type IMO

**Comment by albe** [comment]
It's the negotiated media type of the accepted response types requested against the supported types of the controller. So that's exactly what the response should return, no?

```php
$mediaType = MediaTypeHelper::negotiateMediaType(MediaTypeHelper::determineAcceptedMediaTypes($request->getHttpRequest()), $this->supportedMediaTypes);
```

**Comment by bwaidelich** [comment]
> It's the negotiated media type of the accepted response

ah, yes of course. You're right!

**Comment by albe** [comment]
Note: The test nicely fails with an empty content-type without the fix in the first commit.

**Review by bwaidelich — APPROVED** [review]
Makes sense (by reading). thanks for taking care!

**Comment by kitsunet** [comment]
This introduced a serious regression with the way responses are merged. With this a ContentType will ALWAYS be set in the ActionResponse which means the if conditions while merging inside the ActionResponse will always be true so no overwriting of the content type can happen from repsonses generated in a view for example. Eg. Fusion responses that override the content type will not be able to do that.

**Comment by bwaidelich** [comment]
> This introduced a serious regression with the way responses are merged

Damn, I had a somewhat weird feeling and shouldn't have added my +1 – even if just "by reading"

**Comment by kitsunet** [comment]
If we want to do that we should do it AFTER the view is rendered and then check if we have a content type set and only if not do this.

**Comment by albe** [comment]
Ugh, didn't predict this :( Yeah, guess the solution is to set it after controller invocation if no content-type is set on the response yet.

**Comment by albe** [comment]
Okay, this is not so simple because:
- `ActionResponse::$contentType` is by default uninitialized
- the getter is typehinted to `: string` (which is wrong, because it could be null)
- the `mergeIntoParentResponse()` method explicitly checks for `null` (also `applyToHttpResponse()`, but `mergeIntoComponentContext()` only checks for "truthy")

I suggest fixing the getter with null coalescing operator and just checking for empty string after invoking the action. Then maybe revisit this class in master

**Pull request merged**
