### PR TITLE
FEATURE: Allow setting validator options for element validators

### PR DESCRIPTION
**Pull request by kitsunet**
The element validators configured for a collection validator couldn't
accept options so far, with this change it is possible to set the
``elementValidatorOptions`` option on the ``CollectionValidator`` to
give options to the element validator.

FLOW-435 #resolve

### CODE REVIEW

**Comment by kdambekalns** [comment]
Would be nice if the test actually checked the options are passed on, otherwise :+1:

**Comment by kitsunet** [comment]
Right, will add a test for that!

**Comment by kitsunet** [comment]
test added, IMHO good to go :+1:

**Comment by aertmann** [comment]
Hey. What about documentation? Is it already documented?

**Comment by kitsunet** [comment]
Right, but I think the validator documentation is automatically generated?

**Pull request merged**
