### PR TITLE
TASK: Include TYPO3Fluid for reflection

### PR DESCRIPTION
**Pull request by albe**
This is needed to be able to generate a XSD schema for the TYPO3 Fluid default ViewHelpers.

Depends on #1638

### CODE REVIEW

**Comment by albe** [comment]
Related to #1636 

@kitsunet Are there any classes in TYPO3Fluid that should definitely NOT be reflected? i.e. should we narrow down the `includeClasses`?

**Comment by albe** [comment]
> [Semantical Error] The annotation "@retrurn" in method TYPO3Fluid\Fluid\ViewHelpers\DebugViewHelper::getValuesOfNonScalarVariable() was never imported.
Did you maybe forget to add a "use" statement for this annotation?

:|

**Comment by albe** [comment]
> 1) Neos\Flow\Tests\Functional\Configuration\ConfigurationValidationTest::configurationValidationTests with data set #4 ('Development', 'Settings')
Settings.Neos.Flow.object.includeClasses -> **expected: type=array found: type=array**

Uhm...

**Comment by ComiR** [comment]
https://github.com/neos/flow-development-collection/blob/bab4abb0d96fbb5e0644c10c10f1fa15be2de332/Neos.Flow/Resources/Private/Schema/Settings/Neos.Flow.object.schema.yaml#L7 seems wrong.
It looks like it should be
```yaml
    items:
      type: array
      required: true
      items: { type: string, required: true }
```
(no expertise here - please test before usage 😉)

**Comment by albe** [comment]
You were right, but that still didn't fix it :/ I'm baffled at why this fails and how this never failed before?

**Comment by kdambekalns** [comment]
This only turned green, because Travis CI seems to install a newer `typo3fluid/fluid` than declared in our dependencies…

**Comment by kdambekalns** [comment]
https://github.com/neos/flow-development-collection/pull/1638 "fixed" this, but only for the dev-collection tests. "Real" use still required `~2.1.3`. To be fixed with https://github.com/neos/flow-development-collection/pull/1757.

**Pull request merged**
