### PR TITLE
TASK: PHP 8.1 deprecations compatibility

### PR DESCRIPTION
**Pull request by kdambekalns**
This tweaks the code so that it runs without deprecations on PHP 8.1.

**Upgrade instructions**

None.

**Review instructions**

None.

**Checklist**

- [x] Code follows the PSR-2 coding style
- [x] Tests have been created, run and adjusted as needed
- [x] The PR is created against the [lowest maintained branch](https://www.neos.io/features/release-roadmap.html)
- [x] Reviewer - PR Title is brief but complete and starts with `FEATURE|TASK|BUGFIX`
- [ ] Reviewer - The first section explains the change briefly for change-logs
- [ ] ~Reviewer - Breaking Changes are marked wit `!!!` and have upgrade-instructions~

### CODE REVIEW

**Comment by kdambekalns** [comment]
Fine, only Psalm complains about redundant casts, well… if they would really be redundant, I'd not have added them, eh? 😎

**Comment by kdambekalns** [comment]
Ping… anyone?

**Review by kitsunet — APPROVED** [review]
Very nice!

**Comment by mhsdesign** [comment]
@kdambekalns just out of interest - did you do this by hand (string replace) or did you use rector or something the like?

**Comment by kdambekalns** [comment]
Manually, supported by PhpStorm code inspection and intentions.

**Pull request merged**
