### PR TITLE
TASK: Create composer manifests with default PSR-4 autoloading

### PR DESCRIPTION
**Pull request by kitsunet**

### CODE REVIEW

**Comment by robertlemke** [comment]
The classes string needs to end with \\ for psr-4

**Comment by kitsunet** [comment]
Good catch, fixed that.

**Comment by albe** [comment]
Wonder where the failing tests come from...

**Comment by kitsunet** [comment]
I guess we do some strange things in the tests that don't adhere to PSR-4, will have a look....

**Comment by kitsunet** [comment]
Ok, test failures should be fixed now, it came from some namespace voodoo we did assuming it would be PSR-0 for all times.

**Comment by albe** [comment]
Ah, hail the all-mighty Voodoo-priests. Gonna take a look again, but looks reasonable

**Comment by kdambekalns** [comment]
So, does the kickstarter create the files in the correct places as well?

**Comment by kitsunet** [comment]
@kdambekalns yes it does :)

**Pull request merged**
