### PR TITLE
[FEATURE] Command for copying resources from one storage to another

### PR DESCRIPTION
**Pull request by robertlemke**
This change introduces a new command ``resource:copy`` which copies all
resources contained in the storage of one collection to another.

This can be used to switch the underlying storage and publication target,
for example from a file system based storage to a cloud storage like AWS S3.

Related: FLOW-387

### CODE REVIEW

**Comment by robertlemke** [comment]
Replaces #55. I'll still push a little follow-up regarding the documentation.

**Comment by robertlemke** [comment]
:+1: looks good to me now. Thanks a lot to @hhoechtl for developing this feature!

**Comment by hhoechtl** [comment]
:+1:

**Comment by kitsunet** [comment]
:+1:

**Pull request merged**
