### PR TITLE
TASK: Rename "TYPO3 Flow" to "Flow" and update URLs

### PR DESCRIPTION
**Pull request by kdambekalns**

### CODE REVIEW

**Comment by kdambekalns** [comment]
Replacement for #57 on the 2.3 branch. This was done manually, and when doing upmerges some more places need to be fixed, but I guess I fixed what needs to be fixed in 2.3.

**Comment by kdambekalns** [comment]
Paging @hhoechtl @albe @bwaidelich @kitsunet :)

**Comment by kdambekalns** [comment]
By the way, renders without warnings/errors…

**Comment by kitsunet** [comment]
:+1:

**Comment by albe** [comment]
:+1: only thing I found is the paragraph about the "WIP" commit title prefix, which is deprecated... I'd still merge as is, as that is independent of this change

**Comment by kdambekalns** [comment]
Yeah, the WIP stuff… IIRC that has been updated in a later branch already. Or not. Well, "unrelated" to this one…

**Pull request merged**
