### PR TITLE
[BUGFIX] Set correct request port if X-Forwarded-Proto is set

### PR DESCRIPTION
**Pull request by robertlemke**
This fixes an issue resulting in wrong rendered URLs if Flow is accepting
request from a load balancer or proxy which is accessed via https
externally, sends the X-Forwarded-Proto header to Nginx but does not
specify the X-Forwarded-Port header.

For example, a load balancer (for example Google HTTP/HTTPS load
balancer) is accessible via https and terminates SSL. The load balancer
communicates with Nginx via http on port 80. Google only sends the
X-Forwarded-Proto header ("https") but not the port. URLs, for example
in an action URI of a form, are rendered wrongly.

An expected URL would be https://example.com/foo.html, however, the
rendered URL is https://example.com:80/foo.html

This change changes the behavior in `Request` so that if the
X-Forwarded-Proto header is set, but the X-Forwarded-Port header isn't,
the port is set to the standard port of the given protocol (80 / 443).

Resolves: FLOW-409

### CODE REVIEW

**Comment by robertlemke** [comment]
Previously pushed as PR #119 but to the wrong branch ...

**Comment by kdambekalns** [comment]
:+1: by reading (including the slight difference to #119)

**Comment by bwaidelich** [comment]
:+1:  by reading

**Comment by kitsunet** [comment]
:+1: by reading. I feel the code is becoming slightly confusing and complex there, but that can be fixed with a future refactoring ;)

**Comment by kitsunet** [comment]
Already wondered why the change makes a modification of the test necessary. Seems the modification is not necessary?

**Comment by robertlemke** [comment]
... because the test was wrong – clearified that with Bastian.

**Comment by kitsunet** [comment]
travis says now it's wrong

**Comment by robertlemke** [comment]
@kitsunet Okay, I didn't completely understand what you meant, now I see. Well, the tests were wrong, so they had to be changed. But the change I pushed for this PR also was wrong (copied the lines from a wrong editor window), it was meant to be identical with the original PR #119. So, here's the fixed version now ...

**Comment by kdambekalns** [comment]
Ah, better now. :+1:

**Comment by kitsunet** [comment]
YAY

**Comment by bwaidelich** [comment]
For the record: I don't really remember why the tests were like they were. But probably they just documented the previous *behavior* rather than testing the *specification*.

**Pull request merged**
