### PR TITLE
[BUGFIX] Documentation example for translating error messages uses wrong parameter name 'key' instead of 'id'

### PR DESCRIPTION
**Pull request by dlubitz**

### CODE REVIEW

**Comment by aertmann** [comment]
:+1: should also be fixed in 2.3 though, but there there's two occurrences that need to be fixed so needs a separate change anyway

**Comment by kdambekalns** [comment]
@aertmann where in 2.3 does this need to be fixed? I find only the equivalent to this one…

**Comment by aertmann** [comment]
https://github.com/neos/flow-development-collection/blob/2.3/TYPO3.Flow/Documentation/TheDefinitiveGuide/PartIII/Internationalization.rst

actually only one occurrence

**Comment by kdambekalns** [comment]
@dlubitz would you close this an create a new one against the 2.3 branch? thanks!

**Comment by dlubitz** [comment]
@kdambekalns Sure. Is there an easy way to do this? Or do I have to create a new branch against 2.3 and commit the change again?

**Comment by kdambekalns** [comment]
No easier way, no… Thanks!

**Comment by dlubitz** [comment]
New PR: https://github.com/neos/flow-development-collection/pull/180

**Pull request closed without merging**
