### PR TITLE
BUGFIX: TypeHandling assumes vendor name to be uppercase

### PR DESCRIPTION
**Pull request by kitsunet**
The TypeHandling PARSE_TYPE_PATTERN assumes vendors in namespace do always
begin with uppercase letters. Reality shows, that this is not the case.
So this changes the regular expression accordingly.

### CODE REVIEW

**Comment by kitsunet** [comment]
👎

**Comment by albe** [comment]
The `$` at the end leads to the whole `@var` string to be parsed, therefore leading to doc-text also be considered, leading to the test failure.

**Comment by kitsunet** [comment]
Ok, I think I have it now. Pretty hard to get right actually...

**Comment by kitsunet** [comment]
Actually this should go to a lower branch...

**Comment by kitsunet** [comment]
Will rebase this to 3.2, needs manual action.

**Comment by skurfuerst** [comment]
:+1: from me :)

**Comment by kdambekalns** [comment]
@skurfuerst for the sake of consistency: we use "reactions" on the PR directly, and 👍 means you actually tested this, ❤️ means you read it and approve

**Comment by skurfuerst** [comment]
@kdambekalns - Thanks :)

FYI: I've quickly discussed with @kitsunet and will backport the change to 3.2 - in Pull Request #441 .

**Comment by skurfuerst** [comment]
Closing, and continuing it in https://github.com/neos/flow-development-collection/pull/441

**Pull request closed without merging**
