### PR TITLE
[TASK] Remove typo3.org SSO provider from Flow

### PR DESCRIPTION
**Pull request by kdambekalns**
This is no longer used and should have never been part of the framework
itself, to begin with.

### CODE REVIEW

**Comment by robertlemke** [comment]
:+1:

**Comment by kitsunet** [comment]
:+1:

**Comment by kitsunet** [comment]
Ok I missed that this is for 2.3, I wouldn't have :+1: in that case. It didn't even occur to me to remove a class from a released version....

**Comment by robertlemke** [comment]
@kitsunet but I think there's really no one who can use that feature, because you would need root access to typo3.org in order to do so.

**Comment by kitsunet** [comment]
I am not sure if maybe http://forger.typo3.org/ uses it^^

**Pull request merged**
