### PR TITLE
TASK: Avoid rendering of meta http-equiv if location headers are sent

### PR DESCRIPTION
**Pull request by mficzel**
Now meta http-equiv is only rendered if a delay is requested.

### CODE REVIEW

**Comment by albe** [comment]
Looks good, but out of curiosity: did this not work with delay===0 previously?

**Comment by kdambekalns** [comment]
It would have been nice to know why this is needed. Does it fix a bug? I understand with a Location header the content is useless. but still… this even changes the observable behavior of the system. :)

@albe no, the content was set unconditionally before…

**Comment by albe** [comment]
That's what I was aiming at :) Though probably needless (or maybe not for some archaic clients?) I don't see it being disfunctional before the change. Since master will be next major, it's ok either way, but maybe deserves a bit more reasoning explanation.

**Comment by mficzel** [comment]
@kdambekalns @albe As far as i understand the topic meta http-equiv was not a feature for stupid clients. It was for server-environments that were not able to control the headers. I am pretty sure that flow will not run in such environments anyways so those bits are just waste.

**Comment by kitsunet** [comment]
No, I am pretty sure it was for clients that didn't understand headers at some point. Although I cannot imagine what client that would be still these days. IMHO cleanup is good and an empty redirect is definitely preferable.

I did a quick research:
Location is around since HTTP/1.0, the W3C discourages use of http-equiv refresh for redirecting (it can make sense for other uses, eg. periodical content refresh without JS). Finally a search didn't turn up any results for clients that do not support location headers.

**Pull request merged**
