### PR TITLE
[!!!][TASK] Defer initialisation of View

### PR DESCRIPTION
**Pull request by kitsunet**
Resolving and initialisation of a view are now deferred to after
the action was called so that it only happens if the view is
actually needed.

This can be breaking if you rely on instanceof checks on the view,
because the view will always be a DependencyProxy. You need to call
`_activateDependency()` on the view to actually resolve it, before
checking the object type.

### CODE REVIEW

**Comment by robertlemke** [comment]
How much speed improvement will this give, roughly speaking? Because I guess it might be a breaking change for (a very few) some.

**Comment by kitsunet** [comment]
Yeah, this is also a quick take over from gerrit. I will brush it up and add some numbers...

**Comment by kitsunet** [comment]
And TBH, with this I am also not sure if the breakiness isn't too much :)

**Comment by kdambekalns** [comment]
Let's bury this for good…

**Pull request closed without merging**
