### PR TITLE
[TASK] Replace Security_Randomizer with PHP7 random functions

### PR DESCRIPTION
**Pull request by kitsunet**
Replaces the old Security_Randomizer that we shipped with Flow
by random_bytes and random_int that come with PHP7 and adds a
polyfill library for lower versions.

### CODE REVIEW

**Comment by kitsunet** [comment]
Replaces #5

**Comment by kitsunet** [comment]
Travis doesn't checkout dependencies, so tests won't work correctly.

**Comment by foerthner** [comment]
Looks really good to me. So +1 by reading! Also the functional tests run fine. I just had problems running unit tests, as the library seems not to be loaded in the testing context. As soon as this is fixed, I guess this one can go in.

**Comment by kitsunet** [comment]
Sorry @foerthner I will probably rework this change again because I just was remembered that PHP7 brings new methods for secure random data and there is a polyfill for lower versions. I think that makes even more sense to use because then we can just remove the dependency when we support only PHP7.

So :-1: please wait for new change

Note to self: https://github.com/paragonie/random_compat

**Comment by kitsunet** [comment]
There we go... :+1: again

**Comment by kdambekalns** [comment]
Looks good, but… is the polyfill as good as the real thing?

**Comment by kitsunet** [comment]
It can be considere quite good. Depends on your system obviously as it uses the usual sources like openssl, urandom etc. etc.
But the company seems to have a solid understanding of security, also it supports and suggests libsodium php extension (https://download.libsodium.org/doc/) which seems to be pretty good.
Additionally they list a handful of people that reviewed it one of them being the author of the first library (ircmaxwell) that I suggested.

**Comment by kdambekalns** [comment]
Ok, sounds good.

**Comment by kdambekalns** [comment]
Just merged master into this, to resolve the conflict (`composer.json`, trivial one).

**Comment by kitsunet** [comment]
thanks

**Comment by kdambekalns** [comment]
Ran unit and functional tests locally with PHP 7: :ok: 
Ran unit and functional tests locally with PHP 5.6: :ok: 

:+1:

**Comment by kitsunet** [comment]
Yay, a +1 from Andi would be great, then this should be good to go IMHO

**Comment by foerthner** [comment]
yep, I'm at it. you already can have :+1: by reading. Tests are currently running...

**Comment by foerthner** [comment]
Ok, another :+1: for running tests on PHP 5.5. I guess this one can be merged now!

**Pull request merged**
