### PR TITLE
FEATURE: Command to generate key pair for RsaWalletService

### PR DESCRIPTION
**Pull request by kdambekalns**
A new CLI command to generate a key pair:

  ./ flow security:generatekeypair

### CODE REVIEW

**Comment by kdambekalns** [comment]
@foerthner @hlubek

**Comment by foerthner** [comment]
Thanks, Karsten! Looks good by reading!

**Comment by RafaelKa** [comment]
What about ECDSA? 
I mean if EcdsaWalletService is introduced in Flow, how to use this command?

**Comment by kdambekalns** [comment]
Well, then we could add a type option. But adding that now seems useless, and the import commands would also need to be adjusted in that case… So, no blocker IMHO. Agreed?

**Comment by RafaelKa** [comment]
@kdambekalns yes, agreed

**Comment by kitsunet** [comment]
:+1:

**Pull request merged**
