### PR TITLE
BUGFIX: Respect given locale when checking general translation path

### PR DESCRIPTION
**Pull request by nezaniel**
for label overrides

This seems to have been forgotten in the original implementation and lead to inconsistent behavior when override labels were present in multiple languages

### CODE REVIEW

**Comment by albe** [comment]
I didn't even know this feature existed... and it's also not documented (http://flowframework.readthedocs.io/en/stable/TheDefinitiveGuide/PartIII/Internationalization.html#file-locations-and-naming).

Serious question: When/why would one place a folder of Translations in the `Data` directory of the Flow installation?

**Comment by nezaniel** [comment]
You would put translations there if they are imported from a 3rd party system and thus cannot go to your package repository.

This behaviour was introduced in 4.2 and as it seems I have been sloppy on documentation... It's definitively a new feature but non-breaking since it doesn't affect the current behaviour if no files are found there.

**Comment by albe** [comment]
Ok, then see my comment as a "please document this feature" request :)

**Comment by nezaniel** [comment]
Will do, as soon as I've written the missing tests :)

**Comment by albe** [comment]
Thanks, that looks good. Now only the `globalTranslationPath` setting needs to be added to the Settings Schema, then the test will be green too and this should be ready to merge :)

**Comment by albe** [comment]
Thanks :) Would merge this once Travis passes this weekend if no one objects.

**Comment by nezaniel** [comment]
Done. There seems to be an issue with the test using the vfs... Is there anything I can do about that?

**Comment by albe** [comment]
I restarted the job. There were also some issues with connecting to PPA repository, so I assume it was a temporary connectivity issue.

**Comment by albe** [comment]
Ok, that wasn't the issue apparently... need to investigate, but the test failure shouldn't really be related to this afais...

**Comment by nezaniel** [comment]
you mean other tests that initialize the i18n stuff will indirectly invoke the service without explicitly invoking the vfs?
In that case I'd have to remove that part of the test config and somehow brute force-inject the path where it is used, correct?

**Comment by albe** [comment]
I had to think for a few moments myself, but yeah, I think that would be a good solution.

**Comment by mficzel** [comment]
I added a pr for this branch https://github.com/CORE4/flow-development-collection/pull/1

Basically three things were done in there: 
- Use localeFallbackChain
- merge current 4.2 branch into the pr 
- fix the tests by placing the globalTranslationPath in one of the mocked packages

**Comment by mficzel** [comment]
I found another small issue during testing https://github.com/CORE4/flow-development-collection/pull/2 

Without this change a global translation that in the local fallback chain would override a
better suiting translation from a package.

**Comment by kdambekalns** [comment]
Do I get it right that despite three approvalsthe PR to the PR by @mficzel needs to be merged first? If that's the case, please "request changes" next time, @mficzel :)

**Pull request merged**
