### PR TITLE
[BUGFIX] avoid problem with loading files in simplexml

### LINKED ISSUE #1598: Possible problem with xml php bug in \Neos\Flow\I18n\AbstractXmlParser::getRootNode
### Description

Possible problem with xml php bug in '\Neos\Flow\I18n\AbstractXmlParser::getRootNode'

grafik

### Steps to Reproduce

see https://bugs.php.net/bug.php?id=62577

#### Expected behavior

load xml file

#### Actual behavior

```
Packages/Framework/Neos.Flow/Classes/I18n/AbstractXmlParser.php: Parsing the XML file failed. These error were reported:
failed to load external entity "resource://Neos.Flow/Private/I18n/CLDR/Sources/main/root.xml" (line 0, column 0)
failed to load external entity "resource://Neos.Flow/Private/I18n/CLDR/Sources/main/root.xml" (line 0, column 0)
```

### Affected Versions

Flow: 3.x, 4.x, 5.x

You can get this information by running `composer show`.

### PR DESCRIPTION
**Pull request by kaystrobach**
Workaround for https://bugs.php.net/bug.php?id=62577

fixes #1598

**What I did**

* applied PHP Storm Workaround

**How to verify it**

File is loading, tests pass

**Checklist**

- [ ] Code follows the PSR-2 coding style
- [ ] Tests have been created, run and adjusted as needed
- [ ] The PR is created against the [lowest maintained branch](https://www.neos.io/features/release-roadmap.html)

### CODE REVIEW

**Comment by kaystrobach** [comment]
Yes

**Comment by kaystrobach** [comment]
wasn't there an option to change the parent branch of a PR without using force push?

Anyway the line is the same in all versions.

**Comment by albe** [comment]
You can change the target by editing the head of the PR. However that only works for changing target upwards, since we do upmerging. The other direction will end up with hundreds of commits from the higher versions

**Comment by kdambekalns** [comment]
I am not sure, the issue is seen as a workaround for outdated libxml by some. But I guess it does not harm either. :)

**Comment by kaystrobach** [comment]
it hits me on debian 8 ... with php 7.2

**Comment by kdambekalns** [comment]
See https://github.com/neos/flow-development-collection/pull/1600

**Pull request closed without merging**
