### PR TITLE
TASK: Add required attribute to password ViewHelper

### PR DESCRIPTION
**Pull request by khuppenbauer**

### CODE REVIEW

**Comment by kitsunet** [comment]
travis is failing currntly due to https://jira.neos.io/browse/FLOW-447

**Comment by daniellienert** [comment]
Hey Kerstin,
would be nice if you extend the PasswordViewHelperTest by this property.
Cheers, Daniel

**Comment by kitsunet** [comment]
restarting travis...

**Comment by kdambekalns** [comment]
@kitsunet - you can restart Travis builds from the build page on Travis…

**Comment by kdambekalns** [comment]
@khuppenbauer - would you be up for adjusting the test as @daniellienert suggested?

**Comment by khuppenbauer** [comment]
@daniellienert @kdambekalns tried to add it now - sorry for the delay

**Pull request merged**
