### PR TITLE
[TASK] update code example

### PR DESCRIPTION
**Pull request by dnepro**

### CODE REVIEW

**Comment by dfeyer** [comment]
@dnepro Can you update this PR, based on previous comment ? Thanks

**Comment by dnepro** [comment]
Of course i can, but really sorry that i just now read that, i was a bit sick etc.
Thanks for the feedback :)

**Comment by dfeyer** [comment]
:+1: Thanks for taking care @dnepro for me it's merge ready now

**Comment by hlubek** [comment]
:+1: Looks good now, commits should be squashed before merging

**Comment by hlubek** [comment]
Merged with 100abaa29b7e721733f416ec7394797d76635c37

**Pull request closed without merging**
