### PR TITLE
FEATURE: Add methods getSimpleCache PSR-16 and getCacheItemPool PSR-6 to the cacheManager

### PR DESCRIPTION
**Pull request by mficzel**
The methods create PSR Frontends for the cache with the given identifier. This allows to configure psr caches via
objects and caches yaml. This is an improvement as the included factories are not that easy to use.

The following settings in Objects.yaml allow to inject PSR Caches into Flow Classes:
```
Vendor\Site\Service:

  properties:
    simpleCacheProperty:
      object:
        factoryObjectName: Neos\Flow\Cache\CacheManager
        factoryMethodName: getSimpleCache
        arguments:
          1:
            value: Cache_Identifier_1

    cachePoolProperty:
      object:
        factoryObjectName: Neos\Flow\Cache\CacheManager
        factoryMethodName: getCacheItemPool
        arguments:
          1:
            value: Cache_Identifier_2
```

!!! While possible it is not advisible to access the same cache with multiple Interfaces as the storage formats may differ. !!!

Resolves: #2690 

**Checklist**

- [x] Code follows the PSR-2 coding style
- [x] Tests have been created, run and adjusted as needed
- [x] Docs are adjusted
- [x] The PR is created against the [lowest maintained branch](https://www.neos.io/features/release-roadmap.html)

### CODE REVIEW

**Comment by sorenmalling** [comment]
@mficzel Can you create a corresponding issue that this PR can link to?

**Comment by sorenmalling** [comment]
How is this different from the possibilities today of injecting a configured cache?

**Comment by mficzel** [comment]
@sorenmalling it allows to get instances of the psr Cache classes. Those are different from flowCache frontends but external libraries likely need those for caching.

**Comment by mficzel** [comment]
@kitsunet I remember us discussing how the psr caches should be instantiated back then. I think back then you planned something similar but for some reason we decided to only provide the psr factories back then.

Had some use cases in the meantime where i would have liked the option to inject those cache-interfaces.

**Comment by albe** [comment]
Just for reference, with the PSR factories of `Neos\Cache\Psr` one could inject a cache, but needs to define the backend class and options everytime. So the benefit is primarily that our existing cache configurations can be used to configure PSR caches, right?

> !!! While possible it is not advisible to access the same cache with multiple Interfaces. !!!

Yeah, that's really a pandora box waiting to be opened. I see no good way around that though

**Review by albe — APPROVED** [review]
Generally approve. It's nice to be able to configure PSR caches and inject them like Flow caches.

**Comment by sorenmalling** [comment]
Can the documentation be extended with a explanation on why it's not a good thing to access the same vacate with multiple interfaces?

**Comment by mficzel** [comment]
@sorenmalling changed
> !!! While possible it is not advisible to access the same cache with multiple Interfaces. !!!
to 
> !!! While possible it is not advisible to access the same cache with multiple Interfaces as the storage formats may differ. !!!
As already was in the docs

**Review by kdambekalns — APPROVED** [review]
Looks good by reading.

I guess people will shoot themselves in the foot by accessing the same cache from two sides, but… 🤷‍♂️

**Pull request merged**
