### PR TITLE
[TASK] Apply MIT license to the Flow framework

### PR DESCRIPTION
**Pull request by kdambekalns**
This change adjusts all file headers to state the code is under the MIT
license now. It removes the use of the name TYPO3 in comments along the
way.

Our reasoning for the license change has been explained at
 https://www.neos.io/news/why-mit-license-for-flow-makes-sense.html
and the TYPO3 Association has published the decision at
 http://typo3.org/news/article/the-neos-team-and-the-typo3-association-sign-agreement/

With this change, the need for a CLA is gone.

### CODE REVIEW

**Comment by kdambekalns** [comment]
@aertmann and @kitsunet said _just merge it_…

**Comment by aertmann** [comment]
:+1:

**Comment by bwaidelich** [comment]
> +646 −1,484
I like!

But LocaleCollectionTest.php now contains a syntax error - just kidding, I didn't check all files ;)

**Comment by kdambekalns** [comment]
HARHAR. See https://github.com/neos/flow-development-collection/pull/58 ;)

**Pull request merged**
