### PR TITLE
FEATURE: Virtual Object Configuration

### PR DESCRIPTION
**Pull request by bwaidelich**
Work in progress

Resolves: #671

### CODE REVIEW

**Comment by bwaidelich** [comment]
### Usage:

#### Objects.yaml:
```yaml
Flow:SystemLogger:
  className: 'TYPO3\Flow\Log\Logger'
  scope: singleton
  factoryObjectName: 'TYPO3\Flow\Log\LoggerFactory'
  arguments:
    1:
      value: 'SystemLogger'
    2:
      setting: TYPO3.Flow.log.systemLogger.logger
    3:
      setting: TYPO3.Flow.log.systemLogger.backend
    4:
      setting: TYPO3.Flow.log.systemLogger.backendOptions

Flow:SecurityLogger:
  className: 'TYPO3\Flow\Log\Logger'
  scope: singleton
  factoryObjectName: 'TYPO3\Flow\Log\LoggerFactory'
  arguments:
    1:
      value: 'Flow_Security'
    2:
      value: 'TYPO3\Flow\Log\Logger'
    3:
      setting: TYPO3.Flow.log.securityLogger.backend
    4:
      setting: TYPO3.Flow.log.securityLogger.backendOptions
```

#### PHP:
```php
/**
 * @Flow\Inject(name="Flow:SystemLogger")
 * @var LoggerInterface
 */
protected $systemLogger;

/**
 * @Flow\Inject(name="Flow:SecurityLogger")
 * @var LoggerInterface
 */
protected $securityLogger;
```

**Comment by bwaidelich** [comment]
FYI: With the current implementation a "virtual" object is determined by a colon in the object name

**Comment by albe** [comment]
Hm, can we somehow make sure that the `@var` annotation (which gives the class contract that is expected) is actually fulfilled by the injected virtual configuration? As in "Flow:SystemLogger instanceof LoggerInterface" check at compile time.

Otherwise the `@var` annotation will lose its meaning and unexpected failure could result at runtime.

**Comment by bwaidelich** [comment]
> can we somehow make sure that the @var annotation [...] is actually fulfilled [...]

Good point.
In fact, currently the `className` *has* to be specified for virtual objects.

In theory it should also be possible to only specify a factory (i.e. that's possible with interfaces for example).
In that case we'd lose the connection between `@var` annotation and object type – like today

**Comment by kitsunet** [comment]
if this check should happen, then please at compile time. there is nothing that could change the result at runtime, so to avoid speed loss in this sensible area, only compile time checks :)

**Comment by bwaidelich** [comment]
> if this check should happen, then please at compile time

absolutely

**Comment by bwaidelich** [comment]
Closing in favor of #674 as discussed in #671

**Comment by bwaidelich** [comment]
Dang, closed the wrong one

**Comment by jonnitto** [comment]
Ping @bwaidelich

**Comment by bwaidelich** [comment]
This has been closed because it is stale by all means.. But I still have this on my radar and will re-open if I have enough personal itch to finish this one

**Pull request closed without merging**
