### PR TITLE
BUGFIX: Fix count for query across OneToMany joins

### PR DESCRIPTION
**Pull request by tvt**
The `Query->count` now returns the correct count when a criterion is added on a OneToMany relation.

**Review instructions**

The problem is described in details in #3331. Same as PR #3342, but this time against the correct branch.

**Checklist**

- [x] Code follows the PSR-2 coding style
- [x] Tests have been created, run and adjusted as needed
- [x] The PR is created against the [lowest maintained branch](https://www.neos.io/features/release-roadmap.html)
- [ ] Reviewer - PR Title is brief but complete and starts with `FEATURE|TASK|BUGFIX`
- [ ] Reviewer - The first section explains the change briefly for change-logs
- [ ] Reviewer - Breaking Changes are marked with `!!!` and have upgrade-instructions

### CODE REVIEW

**Review by kdambekalns — APPROVED** [review]
👍 by 👀 – unless @Sebobo vetoes this. For me this looks reasonable.

**Comment by tvt** [comment]
Did you get around to testing it @Sebobo?

**Review by Sebobo — APPROVED** [review]
Works for me, thx!

**Comment by tvt** [comment]
Is anything else needed from me to get this merged?

**Pull request merged**
