### PR TITLE
BUGFIX: Fix required versions in composer manifest

### LINKED ISSUE #3168: BUG: neos/flow  9.0.x-dev requires neos ~8.3.0 packages
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The composer.json in the version 9 branch https://github.com/neos/flow/blob/9.0/composer.json requires neos ~8.3.0 packages. This triggers an composer error:

    Problem 1
      - Root composer.json requires neos/flow 9.0.x-dev -> satisfiable by neos/flow[9.0.x-dev].
      - neos/flow 9.0.x-dev requires neos/cache ~8.3.0 -> found neos/cache[8.3.0, ..., 8.3.x-dev] but it conflicts with your root composer.json require (9.0.x-dev).

if you have an early 9er installation like:

        "neos/flow": "9.0.x-dev",
        "neos/cache": "9.0.x-dev",
        "neos/eel": "9.0.x-dev",
        "neos/error-messages": "9.0.x-dev",
        "neos/utility-objecthandling": "9.0.x-dev",
        "neos/utility-mediatypes": "9.0.x-dev",
        "neos/utility-arrays": "9.0.x-dev",
        "neos/utility-files": "9.0.x-dev",
        "neos/utility-opcodecache": "9.0.x-dev",
        "neos/utility-schema": "9.0.x-dev",
        "neos/utility-unicode": "9.0.x-dev",
        "neos/flow-log": "9.0.x-dev",
        "neos/http-factories": "9.0.x-dev",
        "neos/utility-pdo": "9.0.x-dev",
        "neos/fluid-adaptor": "9.0.x-dev",

### Expected Behavior

The composer.json requires neos ~9.0.0 like it has been before

https://github.com/neos/flow/blob/b32fdef71183000a7d13b5bc8e86a4d5ee242486/composer.json

### Steps To Reproduce

_No response_

### Environment

```markdown
- Flow:
- PHP:
```

### Anything else?

Relates: #3035

### PR DESCRIPTION
**Pull request by ru3fu5z**
closes #3168

### CODE REVIEW

**Comment by ahaeslich** [comment]
Thank you. I think we should target 7.3 here as intended in #3035.

@kdambekalns do you have any idea how to fix this for future releases? (see: https://github.com/neos/flow-development-collection/pull/3035#discussion_r1273657598)

**Comment by kdambekalns** [comment]
> do you have any idea how to fix this for future releases?

Yes, fix the release scripts ;) SCNR

**Comment by kdambekalns** [comment]
See #3186

**Comment by ahaeslich** [comment]
Fixed, see https://github.com/neos/flow-development-collection/issues/3186.

**Pull request closed without merging**
