### PR TITLE
[BUGFIX] Roles are refreshed after setting authentication status

### PR DESCRIPTION
**Pull request by foerthner**
Otherwise getRoles() might act on the wrong value of the overall
authentication status stored in the authentication manager.

### CODE REVIEW

**Comment by aertmann** [comment]
:+1: by reading, although not deep into the subject

**Comment by albe** [comment]
Makes sense and should have no side-effects, :+1: by reading

**Comment by kitsunet** [comment]
👍 by reading

**Comment by bwaidelich** [comment]
:+1:  by reading.
A test to reproduce the broken behavior would be great, but it's probably not easy to do. IIRC I had the issue when the CsrfProtection called `authenticate` very early

**Comment by bwaidelich** [comment]
FYI: I also tested this patch, verifying that it doesn't break an existing application. However I couldn't reproduce the bug - it probably only occurs with multiple concurring authentication tokens

**Pull request merged**
