### PR TITLE
WIP: FEATURE: Add `postCreateProjectCmd` method to the composer installer scripts

### LINKED ISSUE #1867: Configurable tasks to be run upon composer installation
### Description

tbd (see #1852)

### PR DESCRIPTION
**Pull request by mficzel**
The command takes the available option from the path `extra.neos.post-create-project-tasks`
in the main composer manifest.

Each provided option has to provide the keys `description`, `type`, `options` and `hints`:

The types `nothing` and `composer` are supported with a configuration like this:
```
    "extra": {
        "neos": {
            "post-create-project-tasks": {
                "nothing": {
                    "description": "Start with am empty Neos Setup",
                    "type": "nothing",
                    "hints": [
                        "For local development you still have to:",
                        "1. Add database credentials to Configuration/Development/Settings.yaml",
                        "2. Migrate database './flow doctrine:migrate' ",
                        "3. Import site data './flow site:import Neos.Demo'"
                    ]
                },
                "neosDemo": {
                    "description": "Start with the Neos.Demo content",
                    "type": "composer",
                    "options": {
                         "command": "require",
                         "packages": ["neos/demo:dev-master"],
                    }
                    "hints": [
                        "For local development you still have to:",
                        "1. Add database credentials to Configuration/Development/Settings.yaml",
                        "2. Migrate database './flow doctrine:migrate'",
                        "3. Create your site package './flow site:create'"
                    ]
                }
            }
        }
    },
```

Resolves: #1867

### CODE REVIEW

**Comment by mficzel** [comment]
The following command will install a base distribution that has the post-create-project-tasks configured
```
composer create-project --repository '{"type":"vcs", "url":"git@github.com:mficzel/neos-base-distribution.git"}' neos/neos-base-distribution neos-dev-dist-demo-installer dev-task/addPostCreateProjectCmd
```

**Comment by mficzel** [comment]
This is currently a draft as we probably will need a short discussion about the right names and options for this configuration.

**Comment by bwaidelich** [comment]
I added an issue for this in order to simplify release management and to collect higher-level details for the release notes: #1867

**Comment by mficzel** [comment]
I consider this not ready for 5.1 as it requires at least a short discussion about the wording.

**Comment by sorenmalling** [comment]
Hi @mficzel 
Will you take the time to revisit this topic and explain it further in the linked issue?
I like the idea of creating a "wizard-walk-through-like-experience".
We can perhaps target it for the upcoming 7.0 release in december if you say that you have the time

**Comment by mficzel** [comment]
@sorenmalling i would love to finish this but see the need for some discussion to get this right we cannot change this easily afterwards. I will post this as an RFC to discuss.

**Comment by kdambekalns** [comment]
Isn't this history by now?

**Pull request closed without merging**
