### PR TITLE
BUGFIX: Set neos/flow dependencies to self.version

### PR DESCRIPTION
**Pull request by c4ll-m3-j4ck**
Set the package-dependencies to "self.version" to create an installable set of dependencies.

It seems like this upmerge-commit from 8.3 (https://github.com/neos/flow-development-collection/commit/7982ae5c249259033d55ccefa381ab57729f6a87) breaks the installable set of dependencies for the 9.0 branch.

I was able to resolve the dependency-issues by resetting the dependencies to self.version across all flow-development-collection packages.

### CODE REVIEW

**Review by crydotsnake — APPROVED** [review]
Good catch! 💙

**Comment by crydotsnake** [comment]
I didnt saw it at the first place 😅 

But this PR is a duplicate of https://github.com/neos/flow-development-collection/pull/3185

Regarding issue: #3168 

So i will close this then.

But thanks anyway for the contribution ! 💙

**Comment by c4ll-m3-j4ck** [comment]
Hey, 
didn't see that, thank you for checking it out but sorry for the additional work!

**Comment by crydotsnake** [comment]
> Hey, 
> 
> didn't see that, thank you for checking it out but sorry for the additional work!

No problem at all! 🙂

**Pull request closed without merging**
