### PR TITLE
Apply fixes from StyleCI

### PR DESCRIPTION
**Pull request by neos-project**
This pull request applies code style fixes from an analysis carried out by [StyleCI](https://github.styleci.io).

---

For more information, click [here](https://github.styleci.io/analyses/XkeWoP).

### CODE REVIEW

**Comment by bwaidelich** [comment]
@albe why did you close this?

**Comment by albe** [comment]
Huh? I did not do anything in this issue conciously, I'm seeing this for the first time :scream:

**Comment by albe** [comment]
Ah, could it be that there is some code style fix automation in place, and this was a fix triggered by a PR I quickly started and wrongly targeted, then cancelled?

**Comment by bwaidelich** [comment]
Ah, right. That makes sense :)

**Pull request closed without merging**
