### PR TITLE
TASK: Split error messages off

### PR DESCRIPTION
**Pull request by kitsunet**
Separates the Flow error message system used by validation,
schema and property mapping into a separate package and
revises dependencies of the ``Neos.Utility.Schema``.

### CODE REVIEW

**Comment by kitsunet** [comment]
Again, package split. Travis cannot deal with it....
This is fully independent of Flow, which is nice because then the validator framework could become pretty much independent as well.

**Comment by kitsunet** [comment]
updated to master, mergable again.

**Comment by gerhard-boden** [comment]
:+1: by reading

**Comment by kitsunet** [comment]
Updated to solve merge conflicts.

**Comment by kitsunet** [comment]
@kdambekalns Can we get this merged maybe?

**Comment by kdambekalns** [comment]
Looks good, we need to adjust the slicer config and create a new repo. Whoever merges: don't forget that. :)

**Pull request merged**
