### PR TITLE
FEATURE: base64 en-/decoding via Fusion

### PR DESCRIPTION
**Pull request by lisakampert**
**What I did**
An Eel-Helper which uses PHP functions to encode and decode a data-string

### CODE REVIEW

**Comment by kitsunet** [comment]
Hey Lisa, thanks, this is indeed a great idea, I would probably avoid creating a separate class for this though and just add the functionality to the string helper.
What do you think?

**Comment by bwaidelich** [comment]
Nice one! I agree to Christian's comment. Let's add it to the existing `StringHelper` and call it `base64encode()`/`base64decode()`

**Comment by lisakampert** [comment]
It's okay for me, too. But I hadn't found any time to change and adjust it ;-) Hope I'll find time on the weekend!

**Comment by bwaidelich** [comment]
I'll take care

**Comment by kitsunet** [comment]
Will merge when travis is done.

**Pull request merged**
