### PR TITLE
FEATURE: Add optional limit parameter to String.pregReplace

### PR DESCRIPTION
**Pull request by jonnitto**
Resolves: #1863

### CODE REVIEW

**Comment by jonnitto** [comment]
Ups, it seems my IDE add some spaces to other functions, I'll fix this

**Comment by bwaidelich** [comment]
Nice, but the corresponding ui validator should be kept in sync, right?

**Comment by jonnitto** [comment]
I don‘t know exactly what you mean. Where I‘ll find the code I should adapt?

**Comment by bwaidelich** [comment]
> I don‘t know exactly what you mean. Where I‘ll find the code I should adapt?

Hah, sorry for the confusion. I mixed it up with validators and thought we'd need to adjust https://github.com/neos/neos-ui/blob/master/packages/neos-ui-validators/src/RegularExpression/index.tsx. Nevermind :)

**Comment by bwaidelich** [comment]
I added an issue for this in order to simplify release management and to collect higher-level details for the release notes: #1863

**Comment by albe** [comment]
Remaining psalm errors unrelated.

**Comment by markusguenther** [comment]
@albe Could we fix that somehow? (Psalm stuff)

**Comment by albe** [comment]
Yes, but I'll take care in another PR, so let's not block this on that error.

**Pull request merged**
