### PR TITLE
BUGFIX: Update tagFormats to match defined severities

### PR DESCRIPTION
**Pull request by langeland**
Uses the severities descriped in \TYPO3\Flow\Log\LoggerInterface

### CODE REVIEW

**Comment by kdambekalns** [comment]
I'd like to see `info` included to make it B/C and then would be fine with adding to 3.0 even…

**Comment by kitsunet** [comment]
Info is included?

**Comment by kdambekalns** [comment]
Sorry, I meant `success`

**Comment by langeland** [comment]
Hmm.. As such I have no problem with adding `success`, but from what I can see there's no such thing as `success` in the rfc3164. See page 8 Table 2.

And if I look at: `\TYPO3\Flow\Log\Backend\ConsoleBackend::open` then `success` can never be called.

**Comment by kdambekalns** [comment]
That's what you get from purely reading a change: I just saw something that was there, was now gone. If it can never end up there, that obviously doesn't matter at all.

:+1: after reading the related code as well. Still, that looks like a bugfix and should even go into 2.3…

**Comment by kitsunet** [comment]
looks good :+1:

**Pull request merged**
