### PR TITLE
TASK code cleanup ActionRequest

### PR DESCRIPTION
**Pull request by mhsdesign**
solves #2655

I dont know what branch to target, so i go for master. But it should be compatible with 6.3 too. What do you say?

### CODE REVIEW

**Comment by sorenmalling** [comment]
Hi @mhsdesign 

Can you create a corresponding issue that this PR can be referred to? :-)

**Comment by mhsdesign** [comment]
why does the test fail?: https://github.com/neos/flow-development-collection/runs/4573831147?check_suite_focus=true#step:13:32

must be unrelated, but other PRs are green ...

**Comment by sorenmalling** [comment]
> must be unrelated, but other PRs are green ...

Yes, it's unrelated to your change :)

**Comment by mhsdesign** [comment]
hi @sorenmalling could you review this one please ;)

**Review by albe — APPROVED** [review]

**Review by sorenmalling — APPROVED** [review]

**Comment by kitsunet** [comment]
Wait this changes the public API (constructor) and is therefor breaking!?

**Comment by sorenmalling** [comment]
> Wait this changes the public API (constructor) and is therefor breaking!? It shouldn't have been merged like this.

The constructor is protected

**Comment by kitsunet** [comment]
I concur! 👍

**Comment by robertlemke** [comment]
Well, it's protected, but it was declared as `@api` and could be overridden by sub classes – or did I overlook something?

**Comment by kitsunet** [comment]
That is true, the `@api` annotation was what also bothered me originally. Thanks for checking as well :)

**Comment by robertlemke** [comment]
Funnily, you @kitsunet created the TODO initially [some years ago](https://github.com/mhsdesign/flow-development-collection/commit/5b94c184748d7db3e5e716a618fc9b875a7ebb1d#diff-22d9898e57c9c2ce6db0efb5d7d992ff82fc95b2254aef017906a9616d6dfc91R146) …

So, yes, I like the clean-up, but it might not justify a breaking change (according to our `@api` rule), especially without further notice.

**Comment by kitsunet** [comment]
Yep, I am perfectly fine with the changes made, it just needs to be declared breaking. I would assume the amount of extended ActionRequests is not as high as to not do it.

**Comment by albe** [comment]
> So, yes, I like the clean-up, but it might not justify a breaking change (according to our `@api` rule), especially without further notice.

IMO the actual break already happened in https://github.com/mhsdesign/flow-development-collection/commit/e2eb5a37107c2d84f32334f1bd72dd2c49bbde80#diff-22d9898e57c9c2ce6db0efb5d7d992ff82fc95b2254aef017906a9616d6dfc91L139 (i.e. 6.0) and we just forgot to remove the `@api` on the constructor (and make the breaking change clear).

**Pull request merged**
