### PR TITLE
BUGFIX: Avoid warning on empty controller class

### PR DESCRIPTION
**Pull request by daniellienert**

### CODE REVIEW

**Comment by kdambekalns** [comment]
Hm, why would one want to have an empty controller class? Anyway, :+1: by reading.

**Comment by daniellienert** [comment]
If someone does, I don't want to see a red warning ;)

**Comment by albe** [comment]
Would prefer to avoid the additional indenting and instead do an early "continue" statement if methodNames is not an array. Otherwise +1

**Comment by kdambekalns** [comment]
Agree to the early continue - would be consistent with the way it's done earlier in the method.

**Comment by kitsunet** [comment]
Yes please, less nesting = less context in your head while reading :)
Could also do early return on the `if´ around the `foreach` which takes a nesting level away.

**Comment by daniellienert** [comment]
Thanks a lot for the reviews! You are absolutely right.

**Comment by albe** [comment]
:+1: by reading

**Pull request merged**
