### PR TITLE
BUGFIX: Fix rendering of release notes

### PR DESCRIPTION
**Pull request by jonnitto**

### CODE REVIEW

**Comment by jonnitto** [comment]
image

**Comment by jonnitto** [comment]
What do we want to do with the older releases? Basically, we should adjust the older branches…

**Review by markusguenther — APPROVED** [review]
Thanks for taking care :)

**Review by sorenmalling — APPROVED** [review]

**Comment by albe** [comment]
> What do we want to do with the older releases? Basically, we should adjust the older branches…

If someone feels like it, create PRs for those branches - changes don't need to be upmerged from there, only RTD needs to be rerendered.

**Pull request merged**
