### PR TITLE
BUGFIX: Ignore template/psalm annotations

### LINKED ISSUE #1529: Latest Doctrine Collections break reflection (template / psalm annotation)
### Description

Running `doctrine:migrate` is broken with a recent Doctrine Collections versions.

### Steps to Reproduce

1. Update packages
2. run `flow doctrine:migrate`

#### Expected behavior

Migrations are done as needed.

#### Actual behavior

`[Semantical Error] The annotation "@template" in class Doctrine\Common\Collections\Selectable was never imported.` or `[Semantical Error] The annotation "@psalm" in method Doctrine\Common\Collections\Selectable::matching() was never imported.` depending on how far you fixed the issue already.

See also https://github.com/doctrine/collections/issues/180 - the annotations were added with https://github.com/doctrine/collections/pull/177

### Affected Versions

Flow: (at least) 4.3 and up with Doctrine Collections 1.6.0 and up

### PR DESCRIPTION
**Pull request by kdambekalns**
Fixes #1529 by adjusting the configuration.

### CODE REVIEW

**Comment by kdambekalns** [comment]
Ok, the same change existed as https://github.com/neos/flow-development-collection/pull/1528 already, but there wasn't an issue, so I did not realize.

**Comment by kdambekalns** [comment]
But, that PR olny goes against Flow 4.3, but this affects earlier versions as well…

**Comment by dimaip** [comment]
@kdambekalns earlier? I thought 4.3 was the oldest maintained, no?

**Comment by kdambekalns** [comment]
Right, security-fixes only for Neos 2.3 to 3.2.

But if I didn't misread the composer dependencies, we (through transitive dependencies) allow Collections 1.6 in those. So If there is ever the need to update (or install from scratch) any of those, it would break.

**Comment by dimaip** [comment]
Ah, security, keep on forgetting about that....

**Pull request merged**
