### PR TITLE
!!! TASK: Remove PackageManagerInterface

### PR DESCRIPTION
**Pull request by kdambekalns**
Use the `PackageManager` directly instead.

### CODE REVIEW

**Comment by kdambekalns** [comment]
Doh, needs https://github.com/neos/behat/pull/16 to work…

**Comment by kdambekalns** [comment]
Duh, needs https://github.com/neos/flow-welcome/pull/7 to work…

**Comment by kitsunet** [comment]
Goes to show, we use package manager too much...

**Comment by kdambekalns** [comment]
Green now… Yay. Please review…

**Pull request merged**
