### PR TITLE
BUGFIX: Rendering docs produced errors and warnings

### PR DESCRIPTION
**Pull request by DanielSiepmann**
Removed all possible errors and warnings from documentation. This will
allow new errors to be visible as soon as they occur and to reduce the
overall errors.

Some errors lead to non working links or syntax highlighting.

Also fixed indentation at some places. As the indentation wasn't the
same everywhere.

### CODE REVIEW

**Comment by DanielSiepmann** [comment]
Further information can be found as inline comments inside the comment: a69a7bcc19c66ee5969ed93a59224125a172cf69

**Comment by kdambekalns** [comment]
Thanks! Did you check the rendering of the docs in the lower branches (3.1, 3.0, 2.3)? It might be worth the effort to cherry-pick/backport this. WDYT?

**Comment by DanielSiepmann** [comment]
No, I didn't check that but can, and will, do so of course.

**Comment by DanielSiepmann** [comment]
Added PR's for other versions:
- 3.1 - #263
- 3.0 - #264
- 2.3 - #265

**Pull request merged**
