### PR TITLE
TASK: Update documentation about AbstractConditionViewHelper.

### PR DESCRIPTION
**Pull request by DavidSporer**
I tried to create a custom IfViewHelper by extending the AbstractConditionViewHelper and noticed that it was still mentioning to overwrite the render function.
However the render function is not called but rather the evaluateCondition function must be overwritten.
I've basically taken the documentation from the Neos docs and copied it here and made some adjustments.

Let me know if this is ok or not (but current state of the documentation is not correct so it should be changed).

Thanks,
David

### CODE REVIEW

**Comment by albe** [comment]
Awesome! Thanks a lot. Just one thing: can you check at which Typo3 fluid version that changed and then target this at a lower flow version?
If anything lower than Fluid 2.5 we can safely target this at flow 4.3

**Comment by DavidSporer** [comment]
It's been there in Fluid 2.4 as it seems so it should work with Flow 4.3.
But I've just seen this commit: https://github.com/TYPO3/Fluid/commit/a67b31f9e6ecb015d0f47892fce46cf64110fd15

We should keep this in mind but it has been introduced in Fluid 2.6 if I have seen it correctly so that won't work with Flow 4.3 then.

**Comment by albe** [comment]
Good catch.

**Comment by DavidSporer** [comment]
I'll create a new Pull Request for 4.3

**Pull request closed without merging**
