### PR TITLE
BUGFIX: Make ajaxWidgetConfiguration accessible in controller

### PR DESCRIPTION
**Pull request by DanielSiepmann**
**What I did**

* Allow ajax widget configuration to be available in controller.

**How I did it**

* Inverting the existing condition.

**How to verify it**

* See bug report neos/flow-development-collection/issues/896

**Checklist**

- [x] Code follows the PSR-2 coding style
- [ ] Tests have been created, run and adjusted as needed
- [x] The PR is created against the [lowest maintained branch](https://www.neos.io/features/release-roadmap.html)

Fixes: #896

### CODE REVIEW

**Comment by DanielSiepmann** [comment]
This is just a proposal. Feel free to ignore it and provide another solution.

**Comment by albe** [comment]
Fix looks reasonable, I'm just not sure what possible side-effects of this change could be. i.e. are there use cases that would depend on the old (buggy) behaviour?

**Comment by bwaidelich** [comment]
Thanks for your contribution!
Could you please add a quick note what bug this fixes, i.e. _why_ you did this?

**Comment by DanielSiepmann** [comment]
Sure @bwaidelich inside your Widgets, you can modify the widget configuration via `setAjaxWidgetConfiguration` and `setNonAjaxWidgetConfiguration `.

I would expect that using `setNonAjaxWidgetConfiguration` for an ajax widget is the way to go. But since this does not have any effect, the method is useless. That's what this fix is for. An alternative would be to remove the method and calls.

Hope that's enough? Also I tried to be more explicit already in https://github.com/neos/flow-development-collection/issues/896 .

**Comment by bwaidelich** [comment]
Thanks for your comment, I missed the link to the bug report (added a "Fixes" footer now).
Unfortunately this seems to break the `WidgetContextTest` unit test (see https://travis-ci.org/neos/flow-development-collection/jobs/212957918#L737)

**Comment by DanielSiepmann** [comment]
Ok, by investigating the tests I've found out that:
`ajaxWidgetConfiguration` is only available inside of an ajax request, not inside of the controller during the same request. That was what I've tried to fix. But then I just didn't get the idea behind the code and everything should be fine without adjustments.

**Comment by bwaidelich** [comment]
Thanks a lot for investing the time. I wasn't sure either, the code could be more explicit there..

**Pull request closed without merging**
