### PR TITLE
[TASK] Add hasRole to SecurityHelper

### PR DESCRIPTION
**Pull request by kdambekalns**
The SecurityHelper so far only provides getAccount(). This change
adds hasRole() so checks for role assignments are possible within
Eel expressions.

### CODE REVIEW

**Comment by hlubek** [comment]
Could we add a unit test for this?

**Comment by kdambekalns** [comment]
Yes, we can!

**Comment by aertmann** [comment]
:+1: perfect

**Comment by dfeyer** [comment]
:+1: by reading but need a rebase

**Comment by kdambekalns** [comment]
So, this should do it. :)

**Comment by aertmann** [comment]
:+1:

@kdambekalns: feel free to merge

**Pull request merged**
