### PR TITLE
TASK: Allow contains expression on entity properties

### PR DESCRIPTION
**Pull request by kitsunet**
This is very limited on purpose but allows to write policies like this:

`'isType("Whatever\Domain\Model\Party") && (!property("accounts").contains("context.securityContext.account"))'`

### CODE REVIEW

**Comment by kitsunet** [comment]
@kaystrobach That's the PR and branch to watch :)

**Comment by kitsunet** [comment]
@kdambekalns still WIP but adding you already :)

**Comment by kitsunet** [comment]
Alright, this now has a full set of tests for OneToMany and ManyToMany relations.

@kaystrobach I wouldn't refactor that construct in this change to not dilute what this is about. It's complicated enough as is and this code was there before. It can be beautified in a separate refactoring.

**Comment by kaystrobach** [comment]
ok, have you tested this in flow 4.x already, or can i help with testing here?

**Comment by kaystrobach** [comment]
do you need help with the docs?

**Comment by kaystrobach** [comment]
any chance this will be backported to FLOW 4.x?

**Comment by albe** [comment]
Well, this one is practically a feature, so it is supposed to land in master. Personally, I wouldn't mind having it in 4.x, but then, where would we draw the line? I'll let the others decide on this.

**Comment by kaystrobach** [comment]
IMHO no BC, so this can be a new Feature Version (Semver, second number) 😉

**Comment by daniellienert** [comment]
Hey @kitsunet,
Looks good by reading. There is no documentation addition included. Do we have any detailed documentation about the matcher methods at all?

**Comment by kaystrobach** [comment]
There are only examples in the docs

**Comment by kdambekalns** [comment]
Right, the only documentation as at https://neos.readthedocs.io/en/stable/CreatingASite/Security.html, AFAIK. We could definitely need a reference of all shipped "small" and still undocumented operations.

**Comment by kaystrobach** [comment]
@kitsunet will this be backported in 4.x? would be awesome

**Pull request merged**
